import Mathlib
open Polynomial
open scoped BigOperators
open Finset

noncomputable def P_poly (c : ℕ → ℤ) (k : ℕ) : Polynomial ℝ :=
  ∑ i ∈ Finset.Icc 0 k, monomial i (c i : ℝ)
noncomputable def Q_poly (c : ℕ → ℤ) (k : ℕ) : Polynomial ℝ :=
  ∑ i ∈ Finset.Icc 0 k, monomial i (c (((k : ℤ) - (i : ℤ)).toNat) : ℝ)

noncomputable def step_W {m : ℕ} (w : Fin (m + 2) → ℝ) (i : Fin (m + 1)) : ℝ :=
  if i.val = m then w (Fin.castSucc i) + w (Fin.last (m + 1)) else w (Fin.castSucc i)
noncomputable def step_Z {m : ℕ} (w z : Fin (m + 2) → ℝ) (i : Fin (m + 1)) : ℝ :=
  if i.val = m then (w (Fin.castSucc i) * z (Fin.castSucc i) + w (Fin.last (m + 1)) * z (Fin.last (m + 1))) / (w (Fin.castSucc i) + w (Fin.last (m + 1))) else z (Fin.castSucc i)

theorem L_poly_coeff_j (c : ℕ → ℤ) (k : ℕ) (j : ℕ) (hj : j ≤ k) :
  (∑ i ∈ Finset.Icc 0 k, monomial i (c i)).coeff j = c j :=
by
  -- Distribute the coefficient operator over the finite sum
  rw [Polynomial.finset_sum_coeff]

  -- Establish that `j` is within the summation interval `[0, k]`
  have h_mem : j ∈ Finset.Icc 0 k := Finset.mem_Icc.mpr ⟨Nat.zero_le j, hj⟩

  -- Isolate the j-th term from the sum, as all other terms will evaluate to 0
  have H : (∑ i ∈ Finset.Icc 0 k, (monomial i (c i)).coeff j) = (monomial j (c j)).coeff j := by
    refine Finset.sum_eq_single_of_mem j h_mem ?_
    intro i _ hij
    rw [Polynomial.coeff_monomial]
    split_ifs with h_eq
    · -- Contradiction branch: if i = j, it conflicts with hij : i ≠ j
      exact False.elim (hij h_eq)
    · -- Nominal branch: 0 = 0
      rfl

  -- Rewrite the sum as the solitary evaluated term and unfold the final evaluation
  rw [H, Polynomial.coeff_monomial]
  split_ifs with h_eq2
  · -- Nominal branch: c j = c j
    rfl
  · -- Contradiction branch: j ≠ j is impossible
    exact False.elim (h_eq2 rfl)

theorem monomial_zero_eq_zero_helper (i : ℕ) : monomial i (0 : ℤ) = 0 :=
by
  exact Polynomial.monomial_zero_right i

theorem mem_Icc_le_helper (k i : ℕ) (h : i ∈ Finset.Icc 0 k) : i ≤ k :=
by
  rw [Finset.mem_Icc] at h
  exact h.2

theorem poly_coeff_zero_of_eq_zero_helper {p : Polynomial ℤ} (hp : p = 0) (i : ℕ) :
  p.coeff i = 0 :=
by
  rw [hp, Polynomial.coeff_zero]

theorem L_poly_eq_zero_iff_coeff (c : ℕ → ℤ) (k : ℕ) :
  (∑ i ∈ Finset.Icc 0 k, monomial i (c i)) = 0 ↔ ∀ i ≤ k, c i = 0 :=
by
  constructor
  · intro h i hi
    have h_coeff := L_poly_coeff_j c k i hi
    have h_zero := poly_coeff_zero_of_eq_zero_helper h i
    rw [← h_coeff]
    exact h_zero
  · intro h
    apply Finset.sum_eq_zero
    intro i hi
    have hi2 : i ≤ k := mem_Icc_le_helper k i hi
    have hci : c i = 0 := h i hi2
    rw [hci]
    exact monomial_zero_eq_zero_helper i

theorem P_poly_coeff_sum_monomial (c : ℕ → ℤ) (k i : ℕ) :
  (P_poly c k).coeff i = (∑ j ∈ Finset.Icc 0 k, Polynomial.monomial j (c j)).coeff i :=
by
  unfold P_poly
  -- Push the coefficient operator inside the summations and evaluate the monomials
  simp_rw [Polynomial.finset_sum_coeff, Polynomial.coeff_monomial]
  -- Push integer-to-real coercions inside the sums
  push_cast
  -- Match the finite sums on both sides
  refine Finset.sum_congr rfl ?_
  intro j _
  -- Handle the piecewise cases generated by `coeff_monomial`
  split_ifs <;> push_cast <;> rfl

theorem coeff_sum_monomial_eq_sum_ite (c : ℕ → ℤ) (k i : ℕ) :
  (∑ j ∈ Finset.Icc 0 k, Polynomial.monomial j (c j)).coeff i =
  ∑ j ∈ Finset.Icc 0 k, if j = i then c j else (0 : ℤ) :=
by
  simp only [Polynomial.finset_sum_coeff, Polynomial.coeff_monomial]

theorem P_poly_coeff_eq_sum_ite (c : ℕ → ℤ) (k : ℕ) (i : ℕ) :
  (P_poly c k).coeff i = ∑ j ∈ Finset.Icc 0 k, if j = i then c j else (0 : ℤ) :=
by
  rw [P_poly_coeff_sum_monomial]
  rw [coeff_sum_monomial_eq_sum_ite]

theorem sum_ite_eq_Icc_eval (k i : ℕ) (f : ℕ → ℤ) :
  (∑ j ∈ Finset.Icc 0 k, if j = i then f j else (0 : ℤ)) = if i ≤ k then f i else (0 : ℤ) :=
by
  rw [Finset.sum_ite_eq']
  by_cases h : i ≤ k
  · have h' : i ∈ Finset.Icc 0 k := Finset.mem_Icc.mpr ⟨Nat.zero_le i, h⟩
    rw [if_pos h, if_pos h']
  · have h' : i ∉ Finset.Icc 0 k := fun hk => h (Finset.mem_Icc.mp hk).2
    rw [if_neg h, if_neg h']

theorem P_poly_coeff (c : ℕ → ℤ) (k : ℕ) (i : ℕ) :
  (P_poly c k).coeff i = if i ≤ k then c i else 0 :=
by
  rw [P_poly_coeff_eq_sum_ite, sum_ite_eq_Icc_eval]

theorem P_poly_eq_zero_iff_coeff (c : ℕ → ℤ) (k : ℕ) :
  P_poly c k = 0 ↔ ∀ i ≤ k, c i = 0 :=
by
  constructor
  · intro h i hi
    have h_coeff : (P_poly c k).coeff i = 0 := by
      rw [h, Polynomial.coeff_zero]
    rw [P_poly_coeff, if_pos hi] at h_coeff
    exact_mod_cast h_coeff
  · intro h
    ext i
    rw [Polynomial.coeff_zero, P_poly_coeff]
    split_ifs with hi
    · exact_mod_cast h i hi
    · norm_cast

theorem L_poly_ne_zero_iff (c : ℕ → ℤ) (k : ℕ) :
  (∑ i ∈ Finset.Icc 0 k, monomial i (c i)) ≠ 0 ↔ P_poly c k ≠ 0 :=
by
  have h1 := L_poly_eq_zero_iff_coeff c k
  have h2 := P_poly_eq_zero_iff_coeff c k
  constructor
  · intro h hP
    apply h
    exact h1.mpr (h2.mp hP)
  · intro h hL
    apply h
    exact h2.mpr (h1.mp hL)

theorem P_poly_eq_sum_monomial (c : ℕ → ℤ) (k : ℕ) :
  P_poly c k = ∑ i ∈ Finset.Icc 0 k, monomial i (c i : ℝ) :=
rfl

theorem L_poly_aeval_eq (c : ℕ → ℤ) (k : ℕ) (x : ℝ) :
  aeval x (∑ i ∈ Finset.Icc 0 k, monomial i (c i)) = aeval x (P_poly c k) :=
by
  -- Expand P_poly into its explicit sum representation.
  rw [P_poly_eq_sum_monomial]
  -- Push the evaluation algebra-homomorphism inside the sums on both sides simultaneously.
  simp_rw [map_sum, Polynomial.aeval_monomial]
  -- Both sides are now explicit real sums over the same Finset; check they match term-by-term.
  apply Finset.sum_congr rfl
  intro i _
  -- Simplify algebraic casts (algebraMap ℤ ℝ to Int.cast, algebraMap ℝ ℝ to id).
  simp

theorem rootSet_eq_P_poly (c : ℕ → ℤ) (k : ℕ) :
  (∑ i ∈ Finset.Icc 0 k, monomial i (c i)).rootSet ℝ = (P_poly c k).rootSet ℝ :=
by
  ext x
  -- Unfold the definition of the rootset to zero-evaluation and non-zero polynomial checks
  simp only [Polynomial.mem_rootSet, L_poly_ne_zero_iff, L_poly_aeval_eq]

theorem P_poly_coeff_zero_of_ge {c : ℕ → ℤ} {k : ℕ} (hck : c k = 0) {i : ℕ} (hi : k ≤ i) :
  (P_poly c k).coeff i = 0 :=
by
  rw [P_poly_coeff]
  split_ifs with h
  · have : i = k := le_antisymm h hi
    subst this
    simp [hck]
  · simp

theorem P_poly_natDegree_lt {c : ℕ → ℤ} {k : ℕ} (hk : 0 < k) (hck : c k = 0) :
  (P_poly c k).natDegree < k :=
by
  by_cases hp : P_poly c k = 0
  · -- Case 1: The polynomial is identically zero
    rw [hp, Polynomial.natDegree_zero]
    exact hk
  · -- Case 2: The polynomial is non-zero
    by_contra h_contra
    -- Assuming by contradiction that the degree is >= k
    have h1 : k ≤ (P_poly c k).natDegree := by omega

    -- The coefficient at the natural degree must then be exactly 0
    have h2 : (P_poly c k).coeff (P_poly c k).natDegree = 0 := P_poly_coeff_zero_of_ge hck h1

    -- However, the coefficient at the natural degree is precisely the leading coefficient
    have h3 : (P_poly c k).leadingCoeff = 0 := h2

    -- A polynomial with a leading coefficient of 0 must be the zero polynomial
    have h4 : P_poly c k = 0 := Polynomial.leadingCoeff_eq_zero.mp h3

    -- This contradicts our assumption that the polynomial is non-zero
    exact hp h4

theorem c_k_neq_zero_of_roots {c : ℕ → ℤ} {k : ℕ} (hc0 : c 0 ≠ 0)
    (h_roots : k ≤ ((P_poly c k).rootSet ℝ).ncard) : c k ≠ 0 :=
by
  intro hck
  cases k with
  | zero =>
    exact hc0 hck
  | succ k' =>
    have hk : 0 < k' + 1 := Nat.succ_pos k'
    have h_deg : (P_poly c (k' + 1)).natDegree < k' + 1 := P_poly_natDegree_lt hk hck
    have h_le : ((P_poly c (k' + 1)).rootSet ℝ).ncard ≤ (P_poly c (k' + 1)).natDegree :=
      Polynomial.ncard_rootSet_le (P_poly c (k' + 1)) ℝ
    omega

theorem hc0_to_R_ne_zero {c : ℕ → ℤ} (hc0 : c 0 ≠ 0) : (c 0 : ℝ) ≠ 0 :=
by
  exact_mod_cast hc0

theorem aeval_P_poly_eq_sum (c : ℕ → ℤ) (k : ℕ) (x : ℝ) :
  aeval x (P_poly c k) = ∑ i ∈ Finset.Icc 0 k, (c i : ℝ) * x ^ i :=
by
  unfold P_poly
  simp_rw [map_sum]
  apply Finset.sum_congr rfl
  intro i _
  simp

theorem aeval_zero_P_poly {c : ℕ → ℤ} {k : ℕ} :
  aeval (0 : ℝ) (P_poly c k) = (c 0 : ℝ) :=
by
  rw [aeval_P_poly_eq_sum]
  rw [Finset.sum_eq_single 0]
  · rw [pow_zero, mul_one]
  · intro b _ hb_ne
    rw [zero_pow hb_ne, mul_zero]
  · intro h
    exact False.elim (h (Finset.mem_Icc.mpr ⟨Nat.zero_le 0, Nat.zero_le k⟩))

theorem x_ne_zero_of_root_P_poly {c : ℕ → ℤ} {k : ℕ} (hc0 : c 0 ≠ 0) {x : ℝ}
  (hx : x ∈ (P_poly c k).rootSet ℝ) : x ≠ 0 :=
by
  rintro rfl
  have h1 := (Polynomial.mem_rootSet.mp hx).2
  rw [aeval_zero_P_poly] at h1
  exact hc0_to_R_ne_zero hc0 h1

theorem Q_poly_eq_sum_monomial_aux (c : ℕ → ℤ) (k : ℕ) :
    Q_poly c k = ∑ i ∈ Finset.Icc 0 k, monomial i (c (((k : ℤ) - (i : ℤ)).toNat) : ℝ) :=
by
  rfl

theorem Q_poly_coeff_eq {c : ℕ → ℤ} {k : ℕ} (i : ℕ) (hi : i ≤ k) :
  (Q_poly c k).coeff i = (c (((k : ℤ) - (i : ℤ)).toNat) : ℝ) :=
by
  rw [Q_poly_eq_sum_monomial_aux]
  have h_mem : i ∈ Finset.Icc 0 k := by
    rw [Finset.mem_Icc]
    exact ⟨Nat.zero_le i, hi⟩
  simp [Polynomial.coeff_monomial, Finset.sum_ite_eq, h_mem]

theorem Q_poly_coeff_k {c : ℕ → ℤ} {k : ℕ} :
  (Q_poly c k).coeff k = (c 0 : ℝ) :=
by
  -- Apply the general coefficient formula for the specific case i = k
  rw [Q_poly_coeff_eq k le_rfl]
  -- Simplify the subtraction in the index (k : ℤ) - (k : ℤ) to 0
  rw [sub_self]
  -- Int.toNat 0 is definitionally 0, closing the goal
  rfl

theorem Q_poly_ne_zero {c : ℕ → ℤ} {k : ℕ} (hc0 : c 0 ≠ 0) :
  Q_poly c k ≠ 0 :=
by
  intro h
  have h1 : (Q_poly c k).coeff k = (c 0 : ℝ) := Q_poly_coeff_k
  rw [h] at h1
  have h2 : (c 0 : ℝ) ≠ 0 := hc0_to_R_ne_zero hc0
  apply h2
  rw [← h1]
  exact Polynomial.coeff_zero k

theorem aeval_Q_poly_eq_sum (c : ℕ → ℤ) (k : ℕ) (x : ℝ) :
  aeval x (Q_poly c k) = ∑ i ∈ Finset.Icc 0 k, (c (((k : ℤ) - (i : ℤ)).toNat) : ℝ) * x ^ i :=
by
  rw [Q_poly_eq_sum_monomial_aux]
  simp [map_sum, smul_eq_mul]

theorem k_sub_i_add_i_eq_k (k i : ℕ) (hik : i ≤ k) :
  (((k : ℤ) - (i : ℤ)).toNat) + i = k :=
by
  omega

theorem x_pow_k_eq_x_pow_sub_mul_x_pow {x : ℝ} {k i : ℕ} (hik : i ≤ k) :
  x ^ k = x ^ (((k : ℤ) - (i : ℤ)).toNat) * x ^ i :=
by
  -- Combine the powers of `x` on the right-hand side
  rw [← pow_add]
  -- Substitute the simplified exponent using our helper lemma
  rw [k_sub_i_add_i_eq_k k i hik]

theorem x_pow_mul_inv_pow_eq {x : ℝ} (hx : x ≠ 0) {k i : ℕ} (hik : i ≤ k) :
  x ^ k * (x⁻¹) ^ i = x ^ (((k : ℤ) - (i : ℤ)).toNat) :=
by
  rw [x_pow_k_eq_x_pow_sub_mul_x_pow hik]
  rw [inv_pow]
  rw [mul_assoc]
  have hxi : x ^ i ≠ 0 := pow_ne_zero i hx
  rw [mul_inv_cancel₀ hxi]
  rw [mul_one]

theorem reflect_mem_Icc (k i : ℕ) (hi : i ∈ Finset.Icc 0 k) :
  ((k : ℤ) - (i : ℤ)).toNat ∈ Finset.Icc 0 k :=
by
  rw [Finset.mem_Icc] at hi ⊢
  omega

theorem mem_Icc_le_k (k i : ℕ) (h : i ∈ Finset.Icc 0 k) : i ≤ k :=
by
  exact (Finset.mem_Icc.mp h).2

theorem reflect_inj_Icc (k i j : ℕ) (hi : i ∈ Finset.Icc 0 k) (hj : j ∈ Finset.Icc 0 k)
  (h_eq : ((k : ℤ) - (i : ℤ)).toNat = ((k : ℤ) - (j : ℤ)).toNat) : i = j :=
by
  have hi_le := mem_Icc_le_k k i hi
  have hj_le := mem_Icc_le_k k j hj
  omega

theorem reflect_reflect_Icc (k j : ℕ) (hj : j ∈ Finset.Icc 0 k) :
  ((k : ℤ) - (((k : ℤ) - (j : ℤ)).toNat : ℤ)).toNat = j :=
by
  rw [Finset.mem_Icc] at hj
  omega

theorem reflect_surj_Icc (k j : ℕ) (hj : j ∈ Finset.Icc 0 k) :
  ∃ i, ∃ (hi : i ∈ Finset.Icc 0 k), ((k : ℤ) - (i : ℤ)).toNat = j :=
⟨((k : ℤ) - (j : ℤ)).toNat, reflect_mem_Icc k j hj, reflect_reflect_Icc k j hj⟩

theorem sum_Icc_reflect_poly_terms (c : ℕ → ℤ) (k : ℕ) (x : ℝ) :
  ∑ i ∈ Finset.Icc 0 k, (c (((k : ℤ) - (i : ℤ)).toNat) : ℝ) * x ^ (((k : ℤ) - (i : ℤ)).toNat) = ∑ i ∈ Finset.Icc 0 k, (c i : ℝ) * x ^ i :=
by
  apply Finset.sum_bij (fun (i : ℕ) _ => ((k : ℤ) - (i : ℤ)).toNat)
  · intro i hi
    exact reflect_mem_Icc k i hi
  · intro i hi j hj h_eq
    exact reflect_inj_Icc k i j hi hj h_eq
  · intro j hj
    exact reflect_surj_Icc k j hj
  · intro i _
    rfl

theorem x_pow_mul_aeval_Q_poly (c : ℕ → ℤ) (k : ℕ) {x : ℝ} (hx : x ≠ 0) :
  x^k * aeval (x⁻¹) (Q_poly c k) = aeval x (P_poly c k) :=
by
  rw [aeval_Q_poly_eq_sum c k (x⁻¹), aeval_P_poly_eq_sum c k x]
  rw [Finset.mul_sum]
  have h_sum : ∑ i ∈ Finset.Icc 0 k, x ^ k * ((c (((k : ℤ) - (i : ℤ)).toNat) : ℝ) * (x⁻¹) ^ i) =
               ∑ i ∈ Finset.Icc 0 k, (c (((k : ℤ) - (i : ℤ)).toNat) : ℝ) * x ^ (((k : ℤ) - (i : ℤ)).toNat) := by
    apply Finset.sum_congr rfl
    intro i hi
    have hik : i ≤ k := (Finset.mem_Icc.mp hi).right
    rw [← mul_assoc]
    have h_comm : x ^ k * (c (((k : ℤ) - (i : ℤ)).toNat) : ℝ) = (c (((k : ℤ) - (i : ℤ)).toNat) : ℝ) * x ^ k := mul_comm _ _
    rw [h_comm, mul_assoc]
    rw [x_pow_mul_inv_pow_eq hx hik]
  rw [h_sum]
  exact sum_Icc_reflect_poly_terms c k x

theorem aeval_inv_Q_poly_eq_zero {c : ℕ → ℤ} {k : ℕ} {x : ℝ}
  (hx_root : aeval x (P_poly c k) = 0) (hx : x ≠ 0) :
  aeval (x⁻¹) (Q_poly c k) = 0 :=
by
  -- Evaluate P(x) in terms of Q(x⁻¹) multiplied by x^k
  have h_eq : x^k * aeval (x⁻¹) (Q_poly c k) = 0 := by
    rw [x_pow_mul_aeval_Q_poly c k hx, hx_root]

  -- Use the property a * b = 0 ↔ a = 0 ∨ b = 0 to extract the truth
  -- knowing that x^k ≠ 0 ensures aeval (x⁻¹) (Q_poly c k) is strictly the 0 factor
  exact (mul_eq_zero.mp h_eq).resolve_left (pow_ne_zero k hx)

theorem root_P_poly_inv_root_Q_poly {c : ℕ → ℤ} {k : ℕ} (hc0 : c 0 ≠ 0) {x : ℝ}
  (hx : x ∈ (P_poly c k).rootSet ℝ) : x⁻¹ ∈ (Q_poly c k).rootSet ℝ :=
by
  have hP : aeval x (P_poly c k) = 0 := (Polynomial.mem_rootSet.mp hx).2
  have hx_nz : x ≠ 0 := x_ne_zero_of_root_P_poly hc0 hx
  have hQ_nz : Q_poly c k ≠ 0 := Q_poly_ne_zero hc0
  have hQ_root : aeval (x⁻¹) (Q_poly c k) = 0 := aeval_inv_Q_poly_eq_zero hP hx_nz
  exact Polynomial.mem_rootSet.mpr ⟨hQ_nz, hQ_root⟩

theorem rootSet_finite_Q_poly {c : ℕ → ℤ} {k : ℕ} :
  ((Q_poly c k).rootSet ℝ).Finite :=
Polynomial.rootSet_finite (Q_poly c k) ℝ

theorem Q_roots_card_proof {c : ℕ → ℤ} {k : ℕ} (hc0 : c 0 ≠ 0)
    (hP : k ≤ ((P_poly c k).rootSet ℝ).ncard) :
    k ≤ ((Q_poly c k).rootSet ℝ).ncard :=
by

  -- Step A: The transformation x ↦ x⁻¹ is injective over the roots.
  have h_inj : Set.InjOn (fun x : ℝ ↦ x⁻¹) ((P_poly c k).rootSet ℝ) := by
    intro x _ y _ hxy
    have h1 : (x⁻¹)⁻¹ = (y⁻¹)⁻¹ := congrArg (fun z ↦ z⁻¹) hxy
    simp only [inv_inv] at h1
    exact h1

  -- Step B: The image of the roots of P under inversion is a subset of the roots of Q.
  have h_sub : (fun x : ℝ ↦ x⁻¹) '' ((P_poly c k).rootSet ℝ) ⊆ (Q_poly c k).rootSet ℝ := by
    rintro _ ⟨x, hx, rfl⟩
    exact root_P_poly_inv_root_Q_poly hc0 hx

  -- Step C: Applying Mathlib's generic cardinality bounding theorems for mappings between sets.
  have h_img_card : ((fun x : ℝ ↦ x⁻¹) '' ((P_poly c k).rootSet ℝ)).ncard = ((P_poly c k).rootSet ℝ).ncard :=
    Set.ncard_image_of_injOn h_inj

  have h_le : ((fun x : ℝ ↦ x⁻¹) '' ((P_poly c k).rootSet ℝ)).ncard ≤ ((Q_poly c k).rootSet ℝ).ncard :=
    Set.ncard_le_ncard h_sub rootSet_finite_Q_poly

  -- Final algebraic stringing: combining lengths.
  rw [h_img_card] at h_le
  exact le_trans hP h_le

theorem natDegree_sum_le_of_forall (s : Finset ℕ) (d : ℕ) (f : ℕ → Polynomial ℝ)
    (hf : ∀ i ∈ s, (f i).natDegree ≤ d) :
    (∑ i ∈ s, f i).natDegree ≤ d :=
by
  revert hf
  refine Finset.induction_on s ?_ ?_
  · intro _
    rw [sum_empty]
    exact Nat.zero_le d
  · intro a s' ha ih hf
    rw [sum_insert ha]
    have h1 : (f a).natDegree ≤ d := hf a (Finset.mem_insert.mpr (Or.inl rfl))
    have h2 : (∑ i ∈ s', f i).natDegree ≤ d := ih (fun i hi => hf i (Finset.mem_insert.mpr (Or.inr hi)))
    exact le_trans (Polynomial.natDegree_add_le (f a) (∑ i ∈ s', f i)) (max_le h1 h2)

theorem natDegree_monomial_le_i (i : ℕ) (c : ℝ) :
    (monomial i c).natDegree ≤ i :=
by
  exact Polynomial.natDegree_monomial_le c

theorem Q_poly_natDegree_le (c : ℕ → ℤ) (k : ℕ) :
  (Q_poly c k).natDegree ≤ k :=
by
  -- 1. Unfold/Substitute the explicit sum definition of the Q polynomial.
  rw [Q_poly_eq_sum_monomial_aux]

  -- 2. Apply the property that bounds the sum of natural degrees.
  apply natDegree_sum_le_of_forall

  -- 3. Show that for any given generic index `i` in the interval [0, k], its degree is bounded.
  intro i hi

  -- 4. Use transitivity (degree ≤ i and i ≤ k implies degree ≤ k).
  apply le_trans (natDegree_monomial_le_i i _)

  -- 5. Establish `i ≤ k` structurally from the membership in `Finset.Icc 0 k`.
  exact mem_Icc_le_k k i hi

theorem rootSet_ncard_le_roots_card (p : Polynomial ℝ) :
  (p.rootSet ℝ).ncard ≤ p.roots.card :=
by
  have h1 : (p.rootSet ℝ).ncard = (p.aroots ℝ).toFinset.card := by
    exact Set.ncard_coe_finset (p.aroots ℝ).toFinset
  have h2 : p.aroots ℝ = p.roots := by
    -- The algebra map from ℝ to ℝ is the identity, so `aroots` naturally unfolds to this
    change (p.map (RingHom.id ℝ)).roots = p.roots
    rw [Polynomial.map_id]
  rw [h1, h2]
  exact Multiset.toFinset_card_le p.roots

theorem Q_roots_card_eq {c : ℕ → ℤ} {k : ℕ} (hc0 : c 0 ≠ 0)
    (h_card : k ≤ ((Q_poly c k).rootSet ℝ).ncard) :
    (Q_poly c k).roots.card = k :=
by
  have h1 : ((Q_poly c k).rootSet ℝ).ncard ≤ (Q_poly c k).roots.card := rootSet_ncard_le_roots_card (Q_poly c k)
  have h2 : (Q_poly c k).roots.card ≤ (Q_poly c k).natDegree := Polynomial.card_roots' (Q_poly c k)
  have h3 : (Q_poly c k).natDegree ≤ k := Q_poly_natDegree_le c k
  omega

theorem Multiset_esymm_zero_eq {R : Type*} [CommRing R] (S : Multiset R) :
  S.esymm 0 = 1 :=
by
  simp [Multiset.esymm]

theorem Multiset_esymm_empty_pos {R : Type*} [CommRing R] {n : ℕ} (hn : 0 < n) :
  (0 : Multiset R).esymm n = 0 :=
by
  cases n
  · cases hn
  · rfl

theorem esymm_eq_sum_submultisets {R : Type*} [CommRing R] (S : Multiset R) (n : ℕ) :
  S.esymm n = ((S.powersetCard n).map Multiset.prod).sum :=
rfl

theorem powersetCard_cons_lem {R : Type*} [CommRing R] (a : R) (S : Multiset R) (n : ℕ) :
  (a ::ₘ S).powersetCard (n + 1) = S.powersetCard (n + 1) + ((S.powersetCard n).map (fun m => a ::ₘ m)) :=
by
  exact Multiset.powersetCard_cons n a S

theorem sum_prod_add_lem {R : Type*} [CommRing R] (S₁ S₂ : Multiset (Multiset R)) :
  ((S₁ + S₂).map Multiset.prod).sum = (S₁.map Multiset.prod).sum + (S₂.map Multiset.prod).sum :=
by
  rw [Multiset.map_add, Multiset.sum_add]

theorem map_prod_cons_eq {R : Type*} [CommRing R] (a : R) (S : Multiset (Multiset R)) :
  ((S.map (fun m => a ::ₘ m)).map Multiset.prod) = S.map (fun m => a * Multiset.prod m) :=
by
  -- Use the property of mapping a map over a multiset
  rw [Multiset.map_map]

  -- Create an explicit equivalence of the composed mapped functions
  have h : (Multiset.prod ∘ fun m => a ::ₘ m) = (fun m => a * Multiset.prod m) := by
    funext m
    -- Applying the fact that the product of `a ::ₘ m` evaluates to `a * m.prod`
    exact Multiset.prod_cons a m

  -- Rewrite the equality inline to close the proof
  rw [h]

theorem sum_prod_cons_lem {R : Type*} [CommRing R] (a : R) (S : Multiset (Multiset R)) :
  (((S.map (fun m => a ::ₘ m)).map Multiset.prod).sum) = a * ((S.map Multiset.prod).sum) :=
by
  rw [map_prod_cons_eq]
  exact Multiset.sum_map_mul_left

theorem Multiset_esymm_cons_succ {R : Type*} [CommRing R] (a : R) (S : Multiset R) (n : ℕ) :
  (a ::ₘ S).esymm (n + 1) = a * S.esymm n + S.esymm (n + 1) :=
by
  -- Decompose the esymm term into its powerset sum representation
  rw [esymm_eq_sum_submultisets (a ::ₘ S) (n + 1)]

  -- Structurally split the submultisets based on whether they contain 'a'
  rw [powersetCard_cons_lem]

  -- Distribute the multiset map and sum over the multiset addition
  rw [sum_prod_add_lem]

  -- Factor out 'a' from the sum of products of submultisets containing 'a'
  rw [sum_prod_cons_lem]

  -- Fold the expressions back into elementary symmetric polynomial notation
  rw [← esymm_eq_sum_submultisets S (n + 1)]
  rw [← esymm_eq_sum_submultisets S n]

  -- Rearrange the remaining algebraic expression to match the goal exactly
  ring

theorem Multiset_map_sq_sum {R : Type*} [CommRing R] (S : Multiset R) :
  (S.map (fun x => x ^ 2)).sum = (S.esymm 1) ^ 2 - (2 : R) * S.esymm 2 :=
by
  induction S using Multiset.induction_on with
  | empty =>
    -- Base case: The multiset is empty (represented by `0`)
    have h1 : (0 : Multiset R).esymm 1 = 0 := Multiset_esymm_empty_pos (by decide)
    have h2 : (0 : Multiset R).esymm 2 = 0 := Multiset_esymm_empty_pos (by decide)
    simp [h1, h2]
  | cons a s ih =>
    -- Inductive case: The multiset is of the form `a ::ₘ s`
    -- Expand elementary symmetric polynomial degrees 1 and 2
    have h1 : (a ::ₘ s).esymm 1 = a * s.esymm 0 + s.esymm 1 := Multiset_esymm_cons_succ a s 0
    have h2 : (a ::ₘ s).esymm 2 = a * s.esymm 1 + s.esymm 2 := Multiset_esymm_cons_succ a s 1
    -- Evaluate 0-th degree elementary symmetric polynomial to 1
    have h0 : s.esymm 0 = 1 := Multiset_esymm_zero_eq s
    -- Simplify the map and sum over the multiset, and insert the expansions and inductive hypothesis
    simp [h1, h2, h0, ih]
    -- The remainder is pure polynomial algebra mapping mathematically exactly to the inductive equality
    ring

theorem Multiset_map_sq_prod {R : Type*} [CommRing R] (S : Multiset R) :
  (S.map (fun x => x ^ 2)).prod = S.prod ^ 2 :=
by
  refine Multiset.induction_on (p := fun s => (s.map (fun x => x ^ 2)).prod = s.prod ^ 2) S ?_ ?_
  · simp
  · intro a s ih
    simp [ih]
    ring

theorem Multiset_esymm_eq_zero_of_lt {R : Type*} [CommRing R] (S : Multiset R) {n : ℕ} (h : S.card < n) :
  S.esymm n = 0 :=
by
  induction S using Multiset.induction_on generalizing n
  case empty =>
    rw [Multiset.card_zero] at h
    exact Multiset_esymm_empty_pos h
  case cons a S ih =>
    cases n with
    | zero =>
      exfalso
      rw [Multiset.card_cons] at h
      omega
    | succ m =>
      change (a ::ₘ S).esymm (m + 1) = 0
      rw [Multiset_esymm_cons_succ]
      rw [Multiset.card_cons] at h
      have h1 : S.card < m := by omega
      have h2 : S.card < m + 1 := by omega
      rw [ih h1, ih h2, mul_zero, add_zero]

theorem Multiset_esymm_card_eq_prod {R : Type*} [CommRing R] (S : Multiset R) :
  S.esymm S.card = S.prod :=
by
  refine Multiset.induction_on S ?_ ?_
  · -- Base case: S = 0 (empty multiset)
    rw [Multiset.card_zero, Multiset.prod_zero, Multiset_esymm_zero_eq]
  · -- Inductive step: S = a ::ₘ s
    intro a s ih
    -- Unfold card, prod and esymm structurally
    rw [Multiset.card_cons, Multiset.prod_cons, Multiset_esymm_cons_succ]
    -- Apply induction hypothesis
    rw [ih]
    -- Resolve the vanishing term where the symmetric polynomial degree exceeds multiset's card
    have h : s.card < s.card + 1 := by omega
    rw [Multiset_esymm_eq_zero_of_lt s h, add_zero]

theorem Q_poly_natDegree_eq {c : ℕ → ℤ} {k : ℕ} (hc0 : c 0 ≠ 0)
    (h_card : (Q_poly c k).roots.card = k) :
  (Q_poly c k).natDegree = k :=
by
  apply le_antisymm
  · exact Q_poly_natDegree_le c k
  · have h := Polynomial.card_roots' (Q_poly c k)
    rw [h_card] at h
    exact h

theorem k_minus_one_le {k : ℕ} (hk : 1 ≤ k) : (((k : ℤ) - (1 : ℤ)).toNat) ≤ k :=
by
  omega

theorem k_minus_one_toNat_coe (k : ℕ) (hk : 1 ≤ k) :
  ((((k : ℤ) - (1 : ℤ)).toNat) : ℤ) = (k : ℤ) - (1 : ℤ) :=
by
  omega

theorem k_minus_k_minus_one_toNat (k : ℕ) (hk : 1 ≤ k) :
  ((k : ℤ) - ((((k : ℤ) - (1 : ℤ)).toNat) : ℤ)).toNat = 1 :=
by
  rw [k_minus_one_toNat_coe k hk]
  omega

theorem Q_poly_coeff_idx {c : ℕ → ℤ} {k : ℕ} (hk : 1 ≤ k) :
  (Q_poly c k).coeff (((k : ℤ) - (1 : ℤ)).toNat) = (c 1 : ℝ) :=
by
  rw [Q_poly_coeff_eq (((k : ℤ) - (1 : ℤ)).toNat) (k_minus_one_le hk)]
  rw [k_minus_k_minus_one_toNat k hk]

theorem Q_poly_leadingCoeff_eq {c : ℕ → ℤ} {k : ℕ} (hc0 : c 0 ≠ 0)
    (h_card : (Q_poly c k).roots.card = k) :
  (Q_poly c k).leadingCoeff = (c 0 : ℝ) :=
by
  have h : (Q_poly c k).leadingCoeff = (Q_poly c k).coeff (Q_poly c k).natDegree := rfl
  rw [h, Q_poly_natDegree_eq hc0 h_card, Q_poly_coeff_k]

theorem k_minus_one_add {k : ℕ} (hk : 1 ≤ k) : k = 1 + (((k : ℤ) - (1 : ℤ)).toNat) :=
by
  omega

theorem my_nat_add_sub_cancel (a b : ℕ) : a + b - b = a :=
by
  omega

theorem Q_roots_esymm_one {c : ℕ → ℤ} {k : ℕ} (hk : 1 ≤ k) (hc0 : c 0 ≠ 0)
    (h_card : (Q_poly c k).roots.card = k) :
  (Q_poly c k).roots.esymm 1 = - (c 1 : ℝ) / (c 0 : ℝ) :=
by
  have h_deg : (Q_poly c k).natDegree = k := Q_poly_natDegree_eq hc0 h_card
  have h_card_deg : (Q_poly c k).roots.card = (Q_poly c k).natDegree := by
    rw [h_deg]
    exact h_card
  have h_idx_le : (((k : ℤ) - (1 : ℤ)).toNat) ≤ (Q_poly c k).natDegree := by
    rw [h_deg]
    exact k_minus_one_le hk

  -- Apply Mathlib's Vieta's formula
  have vieta := Polynomial.coeff_eq_esymm_roots_of_card h_card_deg h_idx_le

  -- Replace natDegree with 1 + idx
  have H : (Q_poly c k).natDegree = 1 + (((k : ℤ) - (1 : ℤ)).toNat) := by
    rw [h_deg]
    exact k_minus_one_add hk
  rw [H] at vieta

  -- Cancel the subtraction exactly without using simp to preserve the term structure
  have H2 : 1 + (((k : ℤ) - (1 : ℤ)).toNat) - (((k : ℤ) - (1 : ℤ)).toNat) = 1 :=
    my_nat_add_sub_cancel 1 (((k : ℤ) - (1 : ℤ)).toNat)
  rw [H2] at vieta

  -- Substitute explicit polynomial coefficient equivalences
  have h_coeff : (Q_poly c k).coeff (((k : ℤ) - (1 : ℤ)).toNat) = (c 1 : ℝ) := Q_poly_coeff_idx hk
  have h_lc : (Q_poly c k).leadingCoeff = (c 0 : ℝ) := Q_poly_leadingCoeff_eq hc0 h_card
  rw [h_coeff, h_lc] at vieta

  -- Solve the final resulting algebraic equivalence
  have h_eq : - (c 1 : ℝ) = (c 0 : ℝ) * (Q_poly c k).roots.esymm 1 := by
    calc - (c 1 : ℝ) = - ((c 0 : ℝ) * (-1 : ℝ) ^ 1 * (Q_poly c k).roots.esymm 1) := by rw [vieta]
      _ = - ((c 0 : ℝ) * (-1 : ℝ) * (Q_poly c k).roots.esymm 1) := by rw [pow_one]
      _ = (c 0 : ℝ) * (Q_poly c k).roots.esymm 1 := by ring

  have hc0_ne : (c 0 : ℝ) ≠ 0 := hc0_to_R_ne_zero hc0
  rw [h_eq]
  exact (mul_div_cancel_left₀ _ hc0_ne).symm

theorem k_sub_two_mem_Icc {k : ℕ} (hk : 2 ≤ k) :
  (((k : ℤ) - (2 : ℤ)).toNat) ∈ Finset.Icc 0 k :=
by
  rw [Finset.mem_Icc]
  omega

theorem k_sub_k_sub_two_eq_two {k : ℕ} (hk : 2 ≤ k) :
  (((k : ℤ) - ((((k : ℤ) - (2 : ℤ)).toNat) : ℤ)).toNat) = 2 :=
by
  omega

theorem Q_poly_coeff_eval (c : ℕ → ℤ) (k j : ℕ) (hj : j ∈ Finset.Icc 0 k) :
  (Q_poly c k).coeff j = (c (((k : ℤ) - (j : ℤ)).toNat) : ℝ) :=
by
  rw [Q_poly_eq_sum_monomial_aux]
  rw [Polynomial.finset_sum_coeff]
  simp_rw [Polynomial.coeff_monomial]
  rw [Finset.sum_ite_eq']
  rw [if_pos hj]

theorem Q_poly_coeff_k_sub_two {c : ℕ → ℤ} {k : ℕ} (hk : 2 ≤ k) :
  (Q_poly c k).coeff (((k : ℤ) - (2 : ℤ)).toNat) = (c 2 : ℝ) :=
by
  have h_bound := k_sub_two_mem_Icc hk
  have h_eval := Q_poly_coeff_eval c k (((k : ℤ) - (2 : ℤ)).toNat) h_bound
  rw [h_eval, k_sub_k_sub_two_eq_two hk]

theorem d_add_two_eq {k : ℕ} (hk : 2 ≤ k) : k = (((k : ℤ) - (2 : ℤ)).toNat) + (2 : ℕ) :=
by
  omega

theorem d_le_deg {k : ℕ} (hk : 2 ≤ k) : (((k : ℤ) - (2 : ℤ)).toNat) ≤ k :=
by
  omega

theorem vieta_simp (p : Polynomial ℝ) (d : ℕ) (h_card : p.roots.card = p.natDegree)
    (hd_le : d ≤ p.natDegree) (h_diff : p.natDegree = d + (2 : ℕ)) :
  p.coeff d = p.leadingCoeff * p.roots.esymm 2 :=
by
  rw [Polynomial.coeff_eq_esymm_roots_of_card h_card hd_le]
  have hd : p.natDegree - d = (2 : ℕ) := by omega
  rw [hd]
  ring

theorem Q_roots_esymm_two {c : ℕ → ℤ} {k : ℕ} (hk : 2 ≤ k) (hc0 : c 0 ≠ 0)
    (h_card : (Q_poly c k).roots.card = k) :
  (Q_poly c k).roots.esymm 2 = (c 2 : ℝ) / (c 0 : ℝ) :=
by
  -- Obtain polynomial properties
  have h_deg : (Q_poly c k).natDegree = k := Q_poly_natDegree_eq hc0 h_card
  have h_card' : (Q_poly c k).roots.card = (Q_poly c k).natDegree := by
    rw [h_card, h_deg]

  -- Instantiate polynomial degree arithmetic
  have hd_le : (((k : ℤ) - (2 : ℤ)).toNat) ≤ (Q_poly c k).natDegree := by
    rw [h_deg]
    exact d_le_deg hk
  have h_diff : (Q_poly c k).natDegree = (((k : ℤ) - (2 : ℤ)).toNat) + (2 : ℕ) := by
    rw [h_deg]
    exact d_add_two_eq hk

  -- Apply generic abstracted Vieta's Theorem formula
  have h_vieta := vieta_simp (Q_poly c k) (((k : ℤ) - (2 : ℤ)).toNat) h_card' hd_le h_diff

  -- Substitute coefficient and Leading Coefficients bounds specific to Q_poly definition
  have h_coeff := Q_poly_coeff_k_sub_two (c := c) hk
  have h_lc := Q_poly_leadingCoeff_eq hc0 h_card
  rw [h_coeff, h_lc] at h_vieta

  -- Algebraic division isolation logic
  have h0 : (c 0 : ℝ) ≠ 0 := hc0_to_R_ne_zero hc0
  rw [eq_div_iff h0]
  rw [mul_comm]
  exact h_vieta.symm

theorem neg_one_pow_k_sq (k : ℕ) : ((-1 : ℝ) ^ k) ^ 2 = (1 : ℝ) :=
by
  rw [pow_right_comm]
  have h : (-1 : ℝ) ^ 2 = 1 := by norm_num
  rw [h, one_pow]

theorem poly_coeff_sum (s : Finset ℕ) (f : ℕ → Polynomial ℝ) (n : ℕ) :
    (∑ i ∈ s, f i).coeff n = ∑ i ∈ s, (f i).coeff n :=
by
  exact Polynomial.finset_sum_coeff s f n

theorem Q_poly_coeff_zero {c : ℕ → ℤ} {k : ℕ} :
  (Q_poly c k).coeff 0 = (c k : ℝ) :=
by
  -- Express Q_poly as an explicit sum
  rw [Q_poly_eq_sum_monomial_aux]

  -- Distribute coefficient over the finite sum
  rw [poly_coeff_sum]

  -- Isolate the term where i = 0
  have h_sum : ∑ i ∈ Finset.Icc 0 k, (monomial i (c (((k : ℤ) - (i : ℤ)).toNat) : ℝ)).coeff 0 =
      (monomial 0 (c (((k : ℤ) - (0 : ℤ)).toNat) : ℝ)).coeff 0 := by
    apply Finset.sum_eq_single (0 : ℕ)
    · intro b _ hne
      -- For b ≠ 0, the 0-th coefficient of the b-th monomial is strictly 0
      rw [Polynomial.coeff_monomial]
      split_ifs with h
      · exfalso; omega
      · rfl
    · intro hni
      -- It's impossible for 0 not to be in [0, k] since k is a natural number
      exfalso
      apply hni
      rw [Finset.mem_Icc]
      omega

  -- Replace the sum with the evaluated term at i = 0
  rw [h_sum]

  -- Evaluate the monomial coeff at 0
  rw [Polynomial.coeff_monomial]
  split_ifs with h
  · -- Simplify the index expression safely
    have h_eq : (((k : ℤ) - (0 : ℤ)).toNat) = k := by omega
    rw [h_eq]
  · -- Prove contradictory condition is impossible
    exfalso; omega

theorem Q_roots_esymm_k {c : ℕ → ℤ} {k : ℕ} (hc0 : c 0 ≠ 0)
    (h_card : (Q_poly c k).roots.card = k) :
  (Q_poly c k).roots.esymm k = (-1 : ℝ) ^ k * (c k : ℝ) / (c 0 : ℝ) :=
by
  have h_deg : (Q_poly c k).natDegree = k := Q_poly_natDegree_eq hc0 h_card
  have h_lc : (Q_poly c k).leadingCoeff = (c 0 : ℝ) := Q_poly_leadingCoeff_eq hc0 h_card
  have h_c0 : (Q_poly c k).coeff 0 = (c k : ℝ) := Q_poly_coeff_zero

  -- Apply Vieta's formula for the constant term explicitly typed to guide indexing inferences
  have h_vieta : (Q_poly c k).coeff 0 = (Q_poly c k).leadingCoeff * (-1 : ℝ) ^ ((Q_poly c k).natDegree - 0) * (Q_poly c k).roots.esymm ((Q_poly c k).natDegree - 0) :=
    Polynomial.coeff_eq_esymm_roots_of_card (p := Q_poly c k) (by rw [h_deg]; exact h_card) (Nat.zero_le _)

  -- Substitute the known coefficients and degree into the statement
  rw [h_c0, h_lc, h_deg, Nat.sub_zero] at h_vieta

  -- Rearrange to group the right-side elements properly associating to fit division rules
  have h_vieta2 : (c k : ℝ) = (c 0 : ℝ) * ((-1 : ℝ) ^ k * (Q_poly c k).roots.esymm k) := by
    rw [h_vieta, mul_assoc]

  -- Divide by c_0 leveraging algebraic ring cancellations
  have h1 : (c k : ℝ) / (c 0 : ℝ) = (-1 : ℝ) ^ k * (Q_poly c k).roots.esymm k := by
    rw [h_vieta2]
    exact mul_div_cancel_left₀ ((-1 : ℝ) ^ k * (Q_poly c k).roots.esymm k) (hc0_to_R_ne_zero hc0)

  -- Evaluate standard forward evaluation without relying on reversed substitution to avoid matching sub-expressions wrongly
  symm
  calc
    (-1 : ℝ) ^ k * (c k : ℝ) / (c 0 : ℝ) = (-1 : ℝ) ^ k * ((c k : ℝ) / (c 0 : ℝ)) := by ring
    _ = (-1 : ℝ) ^ k * ((-1 : ℝ) ^ k * (Q_poly c k).roots.esymm k) := by rw [h1]
    _ = ((-1 : ℝ) ^ k * (-1 : ℝ) ^ k) * (Q_poly c k).roots.esymm k := by rw [← mul_assoc]
    _ = ((-1 : ℝ) ^ k) ^ 2 * (Q_poly c k).roots.esymm k := by rw [← sq]
    _ = (1 : ℝ) * (Q_poly c k).roots.esymm k := by rw [neg_one_pow_k_sq]
    _ = (Q_poly c k).roots.esymm k := by rw [one_mul]

theorem alg_id_1 (c0 c1 c2 : ℝ) (hc0 : c0 ≠ 0) :
  (- c1 / c0) ^ 2 - (2 : ℝ) * (c2 / c0) = (c1 ^ 2 - (2 : ℝ) * c0 * c2) / (c0 ^ 2) :=
by
  field_simp <;> ring

theorem alg_id_2 (k : ℕ) (c0 ck : ℝ) (hc0 : c0 ≠ 0) :
  ((-1 : ℝ) ^ k * ck / c0) ^ 2 = (ck ^ 2) / (c0 ^ 2) :=
by
  -- Bring the fact that squaring an alternating sign gives 1
  have h : ((-1 : ℝ) ^ k) ^ 2 = (1 : ℝ) := neg_one_pow_k_sq k

  -- Step-by-step rewrite using standard algebraic rules
  -- 1. Distribute the square over division: ((a / b) ^ 2 = a ^ 2 / b ^ 2)
  -- 2. Distribute the square over multiplication: ((a * b) ^ 2 = a ^ 2 * b ^ 2)
  -- 3. Replace the alternating sign squared with 1
  -- 4. Simplify (1 * ck ^ 2) to ck ^ 2
  rw [div_pow, mul_pow, h, one_mul]

theorem Q_roots_sum_sq_and_prod {c : ℕ → ℤ} {k : ℕ} (hk : 2 ≤ k) (hc0 : c 0 ≠ 0)
    (h_card : (Q_poly c k).roots.card = k) :
    (((Q_poly c k).roots.map (fun x => x ^ 2)).sum) = ((c 1 : ℝ) ^ 2 - (2 : ℝ) * (c 0 : ℝ) * (c 2 : ℝ)) / ((c 0 : ℝ) ^ 2) ∧
    (((Q_poly c k).roots.map (fun x => x ^ 2)).prod) = ((c k : ℝ) ^ 2) / ((c 0 : ℝ) ^ 2) :=
by
  constructor
  · rw [Multiset_map_sq_sum]
    have hk1 : 1 ≤ k := by omega
    rw [Q_roots_esymm_one hk1 hc0 h_card]
    rw [Q_roots_esymm_two hk hc0 h_card]
    have hc0_R : (c 0 : ℝ) ≠ 0 := hc0_to_R_ne_zero hc0
    exact alg_id_1 (c 0 : ℝ) (c 1 : ℝ) (c 2 : ℝ) hc0_R
  · rw [Multiset_map_sq_prod]
    rw [← Multiset_esymm_card_eq_prod]
    rw [h_card]
    rw [Q_roots_esymm_k hc0 h_card]
    have hc0_R : (c 0 : ℝ) ≠ 0 := hc0_to_R_ne_zero hc0
    exact alg_id_2 k (c 0 : ℝ) (c k : ℝ) hc0_R

theorem list_sum_map_eq_sum_fin (L : List ℝ) (g : ℝ → ℝ) :
  (L.map g).sum = ∑ i : Fin L.length, g (L.get i) :=
by
  induction L with
  | nil =>
    simp
  | cons a l ih =>
    have h_lhs : ((a :: l).map g).sum = g a + (l.map g).sum := by simp
    rw [h_lhs]
    have h_rhs : (∑ i : Fin (a :: l).length, g ((a :: l).get i)) = ∑ i : Fin (l.length + 1), g ((a :: l).get i) := rfl
    rw [h_rhs]
    rw [Fin.sum_univ_succ]
    have h1 : g ((a :: l).get (0 : Fin (l.length + 1))) = g a := rfl
    have h2 : (∑ i : Fin l.length, g ((a :: l).get (Fin.succ i))) = ∑ i : Fin l.length, g (l.get i) := rfl
    rw [h1, h2, ← ih]

theorem list_prod_map_eq_prod_fin (L : List ℝ) (g : ℝ → ℝ) :
  (L.map g).prod = ∏ i : Fin L.length, g (L.get i) :=
by
  induction L with
  | nil =>
    -- For the base case, the product of an empty list and the product over `Fin 0` are both definitionally 1.
    rfl
  | cons a l ih =>
    -- For the inductive step, we unravel the list's mapping and product.
    rw [List.map_cons, List.prod_cons, ih]
    -- Applying `Fin.prod_univ_succ` matches perfectly with pulling out the 0-th index of the newly formed list.
    exact (Fin.prod_univ_succ fun i => g ((a :: l).get i)).symm

theorem list_sum_prod_eq_fin_get (L : List ℝ) (k : ℕ) (h : L.length = k) :
  ∃ f : Fin k → ℝ,
    (L.map (fun x => x ^ 2)).sum = ∑ i : Fin k, (f i) ^ 2 ∧
    (L.map (fun x => x ^ 2)).prod = ∏ i : Fin k, (f i) ^ 2 :=
by
  -- Substitute `k` with `L.length` everywhere based on the hypothesis `h`
  subst h
  -- Provide the retrieval operation `L.get` as the valid existential witness
  -- and use the sub-lemmas to satisfy the exact shape of both conjunction targets
  exact ⟨fun i => L.get i, list_sum_map_eq_sum_fin L (fun x => x ^ 2), list_prod_map_eq_prod_fin L (fun x => x ^ 2)⟩

theorem multiset_sum_prod_eq_fin (S : Multiset ℝ) (k : ℕ) (hS : S.card = k) :
  ∃ f : Fin k → ℝ,
    (S.map (fun x => x ^ 2)).sum = ∑ i : Fin k, (f i) ^ 2 ∧
    (S.map (fun x => x ^ 2)).prod = ∏ i : Fin k, (f i) ^ 2 :=
by
  revert hS
  refine Quotient.inductionOn S ?_
  intro L hS
  exact list_sum_prod_eq_fin_get L k hS

theorem sum_weights_eq_one (k : ℕ) (hk : 0 < k) : ∑ i : Fin k, ((1 : ℝ) / (k : ℝ)) = 1 :=
by
  -- Since k > 0, its coercion to the reals is non-zero.
  have hk0 : (k : ℝ) ≠ 0 := by positivity

  -- The sum of a constant is the number of terms times the constant.
  rw [Finset.sum_const]

  -- The number of terms in `Fin k` is `k`.
  have h_card : (Finset.univ : Finset (Fin k)).card = k := by simp

  -- Rewrite the cardinality and convert the scalar multiplication (`nsmul`) to real multiplication.
  rw [h_card, nsmul_eq_mul]

  -- Perform the algebraic cancellation safely using `calc` and `ring`.
  calc
    (k : ℝ) * ((1 : ℝ) / (k : ℝ)) = (k : ℝ) / (k : ℝ) := by ring
    _ = 1 := div_self hk0

theorem real_finset_prod_rpow {ι : Type*} (s : Finset ι) (f : ι → ℝ) (r : ℝ) (hf : ∀ i ∈ s, 0 ≤ f i) :
  ∏ i ∈ s, (f i) ^ r = (∏ i ∈ s, f i) ^ r :=
by
  classical
  revert hf
  refine Finset.induction_on s ?_ ?_
  · intro _
    rw [Finset.prod_empty, Finset.prod_empty, Real.one_rpow]
  · intro a s' ha ih hf
    -- Extract products
    rw [Finset.prod_insert ha, Finset.prod_insert ha]

    -- Prove non-negativity for the newly extracted component and the elements of the subset
    have h1 : 0 ≤ f a := hf a (Finset.mem_insert.mpr (Or.inl rfl))
    have h2 : ∀ i ∈ s', 0 ≤ f i := fun i hi => hf i (Finset.mem_insert.mpr (Or.inr hi))

    -- Apply the inductive step to the subset
    rw [ih h2]

    -- Prove that the product computed over the remaining subset is non-negative
    have h3 : 0 ≤ ∏ i ∈ s', f i := Finset.prod_nonneg h2

    -- Distribute the power over the non-negative multiplied elements
    rw [← Real.mul_rpow h1 h3]

theorem prod_rpow_eq_rpow_prod (k : ℕ) (z : Fin k → ℝ) (hz : ∀ i, 0 ≤ z i) :
  ∏ i : Fin k, (z i) ^ ((1 : ℝ) / (k : ℝ)) = (∏ i : Fin k, z i) ^ ((1 : ℝ) / (k : ℝ)) :=
by
  exact real_finset_prod_rpow Finset.univ z ((1 : ℝ) / (k : ℝ)) (fun i _ => hz i)

theorem geom_mean_le_arith_mean_weighted_fin_0 :
  ∀ (w z : Fin 0 → ℝ)
    (hw_nonneg : ∀ i, 0 ≤ w i)
    (hw_sum : ∑ i, w i = 1)
    (hz_nonneg : ∀ i, 0 ≤ z i),
    ∏ i, z i ^ w i ≤ ∑ i, w i * z i :=
by
  intro w z _ hw_sum _
  -- The sum over Fin 0 is evaluating an empty set, which evaluates to 0.
  have h_zero : ∑ i : Fin 0, w i = 0 := by simp
  -- Replace the sum in our hypothesis with 0
  rw [h_zero] at hw_sum
  -- This exposes the contradiction that 0 = 1
  have h_contra : (0 : ℝ) ≠ 1 := by norm_num
  exact False.elim (h_contra hw_sum)

theorem geom_mean_le_arith_mean_weighted_fin_1 :
  ∀ (w z : Fin 1 → ℝ)
    (hw_nonneg : ∀ i, 0 ≤ w i)
    (hw_sum : ∑ i, w i = 1)
    (hz_nonneg : ∀ i, 0 ≤ z i),
    ∏ i, z i ^ w i ≤ ∑ i, w i * z i :=
by
  intro w z _ hw_sum _

  -- The product and sum over `Fin 1` trivially reduce to evaluating the expressions at `default` (which is 0).
  have hp : ∏ i, z i ^ w i = z default ^ w default := Fintype.prod_unique (fun i => z i ^ w i)
  have hs : ∑ i, w i * z i = w default * z default := Fintype.sum_unique (fun i => w i * z i)
  rw [hp, hs]

  -- The sum constraint `∑ i, w i = 1` also reduces, enforcing `w default = 1`.
  have h_sum_w : ∑ i, w i = w default := Fintype.sum_unique w
  rw [h_sum_w] at hw_sum

  -- Substitute the constraint value 1 in place of `w default`
  rw [hw_sum]

  -- Simplify `z ^ 1` to `z` and `1 * z` to `z`.
  -- `rw` will automatically close the reflexive goal `z default ≤ z default` with `rfl`.
  rw [Real.rpow_one, one_mul]

theorem step_W_nonneg {m : ℕ} (w : Fin (m + 2) → ℝ) (hw : ∀ i, 0 ≤ w i) (i : Fin (m + 1)) :
  0 ≤ step_W w i :=
by
  unfold step_W
  try split_ifs
  all_goals
    first
    | exact add_nonneg (hw _) (hw _)
    | exact hw _

theorem step_Z_nonneg {m : ℕ} (w z : Fin (m + 2) → ℝ) (hw : ∀ i, 0 ≤ w i) (hz : ∀ i, 0 ≤ z i) (i : Fin (m + 1)) :
  0 ≤ step_Z w z i :=
by
  unfold step_Z
  split_ifs
  · have hw1 := hw (Fin.castSucc i)
    have hw2 := hw (Fin.last (m + 1))
    have hz1 := hz (Fin.castSucc i)
    have hz2 := hz (Fin.last (m + 1))
    positivity
  · apply hz

theorem step_W_castSucc {m : ℕ} (w : Fin (m + 2) → ℝ) (i : Fin m) :
  step_W w (Fin.castSucc i) = w (Fin.castSucc (Fin.castSucc i)) :=
by
  unfold step_W
  split_ifs with h
  · exfalso
    have h_lt : i.val < m := i.isLt
    revert h
    -- Reduces possible `Fin` equalities (e.g., `Fin.castSucc i = Fin.last m`)
    -- down to their underlying natural number `.val` values.
    simp [Fin.ext_iff]
    omega
  · rfl

theorem step_W_last {m : ℕ} (w : Fin (m + 2) → ℝ) :
  step_W w (Fin.last m) = w (Fin.castSucc (Fin.last m)) + w (Fin.last (m + 1)) :=
by
  unfold step_W
  have h : (Fin.last m).val = m := rfl
  rw [if_pos h]

theorem step_W_sum {m : ℕ} (w : Fin (m + 2) → ℝ) :
  ∑ i : Fin (m + 1), step_W w i = ∑ i : Fin (m + 2), w i :=
by
  have eq1 : ∑ i : Fin (m + 1), step_W w i = (∑ i : Fin m, step_W w (Fin.castSucc i)) + step_W w (Fin.last m) :=
    Fin.sum_univ_castSucc (step_W w)

  have eq2 : ∑ i : Fin (m + 2), w i = (∑ i : Fin (m + 1), w (Fin.castSucc i)) + w (Fin.last (m + 1)) :=
    Fin.sum_univ_castSucc w

  have eq3 : ∑ i : Fin (m + 1), w (Fin.castSucc i) = (∑ i : Fin m, w (Fin.castSucc (Fin.castSucc i))) + w (Fin.castSucc (Fin.last m)) :=
    Fin.sum_univ_castSucc (fun i : Fin (m + 1) => w (Fin.castSucc i))

  -- Substitute all unrolled sum bounds
  rw [eq1, eq2, eq3]

  -- Re-state the inner term using our pre-defined lemma abstraction to resolve the `if-else` within `step_W`
  have h4 : ∑ i : Fin m, step_W w (Fin.castSucc i) = ∑ i : Fin m, w (Fin.castSucc (Fin.castSucc i)) :=
    Finset.sum_congr rfl (fun x _ => step_W_castSucc w x)

  rw [h4, step_W_last w]

  -- The target relies purely on addition associativity to match `A + (B + C) = (A + B) + C`
  rw [← add_assoc]

theorem step_Z_castSucc {m : ℕ} (w z : Fin (m + 2) → ℝ) (i : Fin m) :
  step_Z w z (Fin.castSucc i) = z (Fin.castSucc (Fin.castSucc i)) :=
by
  unfold step_Z
  split_ifs with h
  · exfalso
    have h1 : (Fin.castSucc i).val = i.val := rfl
    have h2 : i.val < m := i.isLt
    omega
  · rfl

theorem step_W_mul_step_Z_castSucc {m : ℕ} (w z : Fin (m + 2) → ℝ) (i : Fin m) :
  step_W w (Fin.castSucc i) * step_Z w z (Fin.castSucc i) =
  w (Fin.castSucc (Fin.castSucc i)) * z (Fin.castSucc (Fin.castSucc i)) :=
by
  rw [step_W_castSucc w i, step_Z_castSucc w z i]

theorem step_Z_last {m : ℕ} (w z : Fin (m + 2) → ℝ) :
  step_Z w z (Fin.last m) = (w (Fin.castSucc (Fin.last m)) * z (Fin.castSucc (Fin.last m)) + w (Fin.last (m + 1)) * z (Fin.last (m + 1))) / (w (Fin.castSucc (Fin.last m)) + w (Fin.last (m + 1))) :=
by
  unfold step_Z
  exact if_pos rfl

theorem step_W_mul_step_Z_last_aux (a b x y : ℝ) (ha : 0 ≤ a) (hb : 0 ≤ b) :
  (a + b) * ((a * x + b * y) / (a + b)) = a * x + b * y :=
by
  by_cases hab : a + b = 0
  · have ha0 : a = 0 := by linarith
    have hb0 : b = 0 := by linarith
    rw [ha0, hb0]
    ring
  · exact mul_div_cancel₀ _ hab

theorem step_W_mul_step_Z_last {m : ℕ} (w z : Fin (m + 2) → ℝ) (hw : ∀ i, 0 ≤ w i) :
  step_W w (Fin.last m) * step_Z w z (Fin.last m) = w (Fin.castSucc (Fin.last m)) * z (Fin.castSucc (Fin.last m)) + w (Fin.last (m + 1)) * z (Fin.last (m + 1)) :=
by
  rw [step_W_last, step_Z_last]
  exact step_W_mul_step_Z_last_aux _ _ _ _ (hw _) (hw _)

theorem sum_step_W_mul_step_Z {m : ℕ} (w z : Fin (m + 2) → ℝ)
  (hw_nonneg : ∀ i : Fin (m + 2), 0 ≤ w i) :
  ∑ i : Fin (m + 1), step_W w i * step_Z w z i = ∑ i : Fin (m + 2), w i * z i :=
by
  have h1 : ∑ i : Fin (m + 1), step_W w i * step_Z w z i = (∑ i : Fin m, step_W w (Fin.castSucc i) * step_Z w z (Fin.castSucc i)) + step_W w (Fin.last m) * step_Z w z (Fin.last m) := by
    exact Fin.sum_univ_castSucc (fun i => step_W w i * step_Z w z i)

  have h2 : ∑ i : Fin (m + 2), w i * z i = (∑ i : Fin (m + 1), w (Fin.castSucc i) * z (Fin.castSucc i)) + w (Fin.last (m + 1)) * z (Fin.last (m + 1)) := by
    exact Fin.sum_univ_castSucc (fun i => w i * z i)

  have h3 : ∑ i : Fin (m + 1), w (Fin.castSucc i) * z (Fin.castSucc i) = (∑ i : Fin m, w (Fin.castSucc (Fin.castSucc i)) * z (Fin.castSucc (Fin.castSucc i))) + w (Fin.castSucc (Fin.last m)) * z (Fin.castSucc (Fin.last m)) := by
    exact Fin.sum_univ_castSucc (fun i => w (Fin.castSucc i) * z (Fin.castSucc i))

  rw [h1, h2, h3]
  rw [step_W_mul_step_Z_last w z hw_nonneg]

  have h_sum : ∑ i : Fin m, step_W w (Fin.castSucc i) * step_Z w z (Fin.castSucc i) = ∑ i : Fin m, w (Fin.castSucc (Fin.castSucc i)) * z (Fin.castSucc (Fin.castSucc i)) := by
    apply Finset.sum_congr rfl
    intro i _
    exact step_W_mul_step_Z_castSucc w z i

  rw [h_sum]
  rw [← add_assoc]

theorem prod_fin_m_plus_two {m : ℕ} (f : Fin (m + 2) → ℝ) :
  ∏ i : Fin (m + 2), f i = (∏ i : Fin m, f (Fin.castSucc (Fin.castSucc i))) * f (Fin.castSucc (Fin.last m)) * f (Fin.last (m + 1)) :=
by
  rw [Fin.prod_univ_castSucc, Fin.prod_univ_castSucc]

theorem prod_fin_m_plus_one {m : ℕ} (g : Fin (m + 1) → ℝ) :
  ∏ i : Fin (m + 1), g i = (∏ i : Fin m, g (Fin.castSucc i)) * g (Fin.last m) :=
Fin.prod_univ_castSucc g

theorem am_gm_weights_sum_eq_one (a b : ℝ) (hab : 0 < a + b) :
  a / (a + b) + b / (a + b) = 1 :=
by
  rw [← add_div]
  exact div_self (ne_of_gt hab)

theorem am_gm_rhs_eq (a b x y : ℝ) :
  (a / (a + b)) * x + (b / (a + b)) * y = (a * x + b * y) / (a + b) :=
by
  ring

theorem am_gm_weighted_two_vars (a b x y : ℝ) (ha : 0 ≤ a) (hb : 0 ≤ b)
    (hx : 0 ≤ x) (hy : 0 ≤ y) (hab : 0 < a + b) :
  x ^ (a / (a + b)) * y ^ (b / (a + b)) ≤ (a * x + b * y) / (a + b) :=
by
  have hw1 : 0 ≤ a / (a + b) := div_nonneg ha (le_of_lt hab)
  have hw2 : 0 ≤ b / (a + b) := div_nonneg hb (le_of_lt hab)
  have hsum : a / (a + b) + b / (a + b) = 1 := am_gm_weights_sum_eq_one a b hab
  have h_am_gm := Real.geom_mean_le_arith_mean2_weighted hw1 hw2 hx hy hsum
  rw [am_gm_rhs_eq a b x y] at h_am_gm
  exact h_am_gm

theorem rpow_mul_nonneg (a b x y : ℝ) (hx : 0 ≤ x) (hy : 0 ≤ y) :
  0 ≤ x ^ (a / (a + b)) * y ^ (b / (a + b)) :=
mul_nonneg (Real.rpow_nonneg hx (a / (a + b))) (Real.rpow_nonneg hy (b / (a + b)))

theorem rpow_nonneg_of_nonneg (x y : ℝ) (hx : 0 ≤ x) : 0 ≤ x ^ y :=
Real.rpow_nonneg hx y

theorem rpow_pow_div_cancel (x a c : ℝ) (hx : 0 ≤ x) (hc : c ≠ 0) :
  (x ^ (a / c)) ^ c = x ^ a :=
by
  calc
    (x ^ (a / c)) ^ c = x ^ ((a / c) * c) := by rw [Real.rpow_mul hx]
    _ = x ^ a := by rw [div_mul_cancel₀ a hc]

theorem mul_rpow_of_nonneg (x y z : ℝ) (hx : 0 ≤ x) (hy : 0 ≤ y) :
  (x * y) ^ z = x ^ z * y ^ z :=
Real.mul_rpow hx hy

theorem rpow_mul_rpow_pow (a b x y : ℝ) (hx : 0 ≤ x) (hy : 0 ≤ y) (hab : a + b ≠ 0) :
  (x ^ (a / (a + b)) * y ^ (b / (a + b))) ^ (a + b) = x ^ a * y ^ b :=
by
  have h1 : 0 ≤ x ^ (a / (a + b)) := rpow_nonneg_of_nonneg x (a / (a + b)) hx
  have h2 : 0 ≤ y ^ (b / (a + b)) := rpow_nonneg_of_nonneg y (b / (a + b)) hy
  rw [mul_rpow_of_nonneg (x ^ (a / (a + b))) (y ^ (b / (a + b))) (a + b) h1 h2]
  rw [rpow_pow_div_cancel x a (a + b) hx hab]
  rw [rpow_pow_div_cancel y b (a + b) hy hab]

theorem two_var_ineq_zero (a b x y : ℝ) (ha : 0 ≤ a) (hb : 0 ≤ b) (hab : a + b = 0) :
  x ^ a * y ^ b ≤ ((a * x + b * y) / (a + b)) ^ (a + b) :=
by
  have ha0 : a = 0 := by linarith
  have hb0 : b = 0 := by linarith
  rw [ha0, hb0]
  simp [Real.rpow_zero]

theorem two_var_ineq (a b x y : ℝ) (ha : 0 ≤ a) (hb : 0 ≤ b) (hx : 0 ≤ x) (hy : 0 ≤ y) :
  x ^ a * y ^ b ≤ ((a * x + b * y) / (a + b)) ^ (a + b) :=
by
  have hab_nonneg : 0 ≤ a + b := add_nonneg ha hb
  cases eq_or_lt_of_le hab_nonneg with
  | inl h_eq =>
    exact two_var_ineq_zero a b x y ha hb h_eq.symm
  | inr hab_pos =>
    have h1 := am_gm_weighted_two_vars a b x y ha hb hx hy hab_pos
    have h2 := rpow_mul_nonneg a b x y hx hy
    have h3 := Real.rpow_le_rpow h2 h1 (le_of_lt hab_pos)
    have hab_ne : a + b ≠ 0 := ne_of_gt hab_pos
    rw [rpow_mul_rpow_pow a b x y hx hy hab_ne] at h3
    exact h3

theorem prod_le_prod_step {m : ℕ} (w z : Fin (m + 2) → ℝ)
  (hw_nonneg : ∀ i : Fin (m + 2), 0 ≤ w i) (hz_nonneg : ∀ i : Fin (m + 2), 0 ≤ z i) :
  ∏ i : Fin (m + 2), z i ^ w i ≤ ∏ i : Fin (m + 1), step_Z w z i ^ step_W w i :=
by
  rw [prod_fin_m_plus_two, prod_fin_m_plus_one]
  have H : (∏ i : Fin m, (step_Z w z (Fin.castSucc i)) ^ (step_W w (Fin.castSucc i))) = ∏ i : Fin m, z (Fin.castSucc (Fin.castSucc i)) ^ w (Fin.castSucc (Fin.castSucc i)) := by
    apply Finset.prod_congr rfl
    intro i _
    rw [step_Z_castSucc, step_W_castSucc]
  rw [H, mul_assoc]
  apply mul_le_mul_of_nonneg_left
  · rw [step_W_last, step_Z_last]
    apply two_var_ineq
    · exact hw_nonneg _
    · exact hw_nonneg _
    · exact hz_nonneg _
    · exact hz_nonneg _
  · apply Finset.prod_nonneg
    intro i _
    apply Real.rpow_nonneg
    exact hz_nonneg _

theorem geom_mean_le_arith_mean_weighted_fin_succ_succ (m : ℕ)
    (ih : ∀ (w z : Fin (m + 1) → ℝ)
      (hw_nonneg : ∀ i, 0 ≤ w i)
      (hw_sum : ∑ i, w i = 1)
      (hz_nonneg : ∀ i, 0 ≤ z i),
      ∏ i, z i ^ w i ≤ ∑ i, w i * z i) :
    ∀ (w z : Fin (m + 2) → ℝ)
      (hw_nonneg : ∀ i, 0 ≤ w i)
      (hw_sum : ∑ i, w i = 1)
      (hz_nonneg : ∀ i, 0 ≤ z i),
      ∏ i, z i ^ w i ≤ ∑ i, w i * z i :=
by
  intro w z hw_nonneg hw_sum hz_nonneg
  have hw'_nonneg : ∀ i, 0 ≤ step_W w i := fun i => step_W_nonneg w hw_nonneg i
  have hz'_nonneg : ∀ i, 0 ≤ step_Z w z i := fun i => step_Z_nonneg w z hw_nonneg hz_nonneg i
  have hw'_sum : ∑ i : Fin (m + 1), step_W w i = 1 := by
    rw [step_W_sum w, hw_sum]
  have H := ih (step_W w) (step_Z w z) hw'_nonneg hw'_sum hz'_nonneg
  calc
    ∏ i, z i ^ w i ≤ ∏ i, step_Z w z i ^ step_W w i := prod_le_prod_step w z hw_nonneg hz_nonneg
    _ ≤ ∑ i, step_W w i * step_Z w z i := H
    _ = ∑ i, w i * z i := sum_step_W_mul_step_Z w z hw_nonneg

theorem geom_mean_le_arith_mean_weighted_fin_n (k : ℕ) :
  ∀ (w z : Fin k → ℝ)
    (hw_nonneg : ∀ i, 0 ≤ w i)
    (hw_sum : ∑ i, w i = 1)
    (hz_nonneg : ∀ i, 0 ≤ z i),
    ∏ i, z i ^ w i ≤ ∑ i, w i * z i :=
by
  induction k with
  | zero => exact geom_mean_le_arith_mean_weighted_fin_0
  | succ m ih =>
    cases m with
    | zero => exact geom_mean_le_arith_mean_weighted_fin_1
    | succ m' => exact geom_mean_le_arith_mean_weighted_fin_succ_succ m' ih

theorem geom_mean_le_arith_mean_weighted_fin (k : ℕ) (w z : Fin k → ℝ)
    (hw_nonneg : ∀ i ∈ (Finset.univ : Finset (Fin k)), 0 ≤ w i)
    (hw_sum : ∑ i ∈ (Finset.univ : Finset (Fin k)), w i = 1)
    (hz_nonneg : ∀ i ∈ (Finset.univ : Finset (Fin k)), 0 ≤ z i) :
    ∏ i ∈ (Finset.univ : Finset (Fin k)), z i ^ w i ≤ ∑ i ∈ (Finset.univ : Finset (Fin k)), w i * z i :=
by
  exact geom_mean_le_arith_mean_weighted_fin_n k w z
    (fun i => hw_nonneg i (Finset.mem_univ i))
    hw_sum
    (fun i => hz_nonneg i (Finset.mem_univ i))

theorem am_gm_finset_sq (k : ℕ) (hk : 0 < k) (f : Fin k → ℝ) :
  (k : ℝ) * (∏ i : Fin k, f i ^ 2) ^ ((1 : ℝ) / (k : ℝ)) ≤ ∑ i : Fin k, f i ^ 2 :=
by
  let w : Fin k → ℝ := fun _ ↦ (1 : ℝ) / (k : ℝ)
  let z : Fin k → ℝ := fun i ↦ f i ^ 2

  have hw_nonneg : ∀ i ∈ (Finset.univ : Finset (Fin k)), 0 ≤ w i := by
    intro _ _
    positivity
  have hw_sum : ∑ i ∈ (Finset.univ : Finset (Fin k)), w i = 1 := by
    exact sum_weights_eq_one k hk
  have hz_nonneg : ∀ i ∈ (Finset.univ : Finset (Fin k)), 0 ≤ z i := by
    intro _ _
    positivity

  -- 1. Obtain the Generalized AM-GM Bound
  have h_am_gm := geom_mean_le_arith_mean_weighted_fin k w z hw_nonneg hw_sum hz_nonneg

  -- 2. Restate definitions clearly into context
  change (∏ i : Fin k, (z i) ^ ((1 : ℝ) / (k : ℝ))) ≤ ∑ i : Fin k, (((1 : ℝ) / (k : ℝ)) * z i) at h_am_gm

  -- 3. Extract the constant weight factor from the sum
  rw [← Finset.mul_sum] at h_am_gm

  -- 4. Convert product of exponents into an exponent of products
  have hz_nonneg_all : ∀ i : Fin k, 0 ≤ z i := fun i ↦ sq_nonneg (f i)
  have h_prod : ∏ i : Fin k, (z i) ^ ((1 : ℝ) / (k : ℝ)) = (∏ i : Fin k, z i) ^ ((1 : ℝ) / (k : ℝ)) :=
    prod_rpow_eq_rpow_prod k z hz_nonneg_all

  rw [h_prod] at h_am_gm

  -- 5. Scale both sides of the inequality strictly by `k`
  have hk_nonneg : (0 : ℝ) ≤ (k : ℝ) := by positivity
  have h_mul := mul_le_mul_of_nonneg_left h_am_gm hk_nonneg

  -- 6. Cancel algebraically using basic explicit field properties
  have h_cancel : (k : ℝ) * (((1 : ℝ) / (k : ℝ)) * ∑ i : Fin k, z i) = ∑ i : Fin k, z i := by
    have hk_pos : (0 : ℝ) < (k : ℝ) := Nat.cast_pos.mpr hk
    have hk_ne : (k : ℝ) ≠ 0 := ne_of_gt hk_pos
    rw [← mul_assoc, mul_div_cancel₀ (1 : ℝ) hk_ne, one_mul]

  rw [h_cancel] at h_mul
  exact h_mul

theorem am_gm_multiset (k : ℕ) (hk : 0 < k) (S : Multiset ℝ) (hS : S.card = k) :
  (k : ℝ) * ((S.map (fun x => x ^ 2)).prod) ^ ((1 : ℝ) / (k : ℝ)) ≤ (S.map (fun x => x ^ 2)).sum :=
by
  obtain ⟨f, h_sum, h_prod⟩ := multiset_sum_prod_eq_fin S k hS
  rw [h_sum, h_prod]
  exact am_gm_finset_sq k hk f

theorem int_sq_ge_one (c : ℤ) (hc : c ≠ 0) : (1 : ℝ) ≤ (c : ℝ) ^ 2 :=
by
  have h1 : 0 < c ^ 2 := sq_pos_of_ne_zero hc
  have h2 : (1 : ℤ) ≤ c ^ 2 := by omega
  exact_mod_cast h2

theorem one_le_k_of_ge_2 (k : ℕ) (hk : 2 ≤ k) : (1 : ℝ) ≤ (k : ℝ) :=
by
  have h : (2 : ℝ) ≤ (k : ℝ) := by exact_mod_cast hk
  linarith

theorem ck_sq_div_c0_sq_rpow_eq (k c0_sq ck_sq : ℝ) (hc0 : 0 < c0_sq) (hck : 0 ≤ ck_sq) :
  (ck_sq / c0_sq) ^ ((1 : ℝ) / k) = ck_sq ^ ((1 : ℝ) / k) / c0_sq ^ ((1 : ℝ) / k) :=
by
  exact Real.div_rpow hck (le_of_lt hc0) ((1 : ℝ) / k)

theorem c0_sq_rpow_sub_eq_div (k c0_sq : ℝ) (hc0 : 0 < c0_sq) :
  c0_sq ^ ((1 : ℝ) - (1 : ℝ) / k) = c0_sq / c0_sq ^ ((1 : ℝ) / k) :=
by
  rw [Real.rpow_sub hc0, Real.rpow_one]

theorem C_bound_lem_eq1 (k c0_sq ck_sq : ℝ) (hc0 : 0 < c0_sq) (hck : 0 ≤ ck_sq) :
  c0_sq * (ck_sq / c0_sq) ^ ((1 : ℝ) / k) = c0_sq ^ ((1 : ℝ) - (1 : ℝ) / k) * ck_sq ^ ((1 : ℝ) / k) :=
by
  rw [ck_sq_div_c0_sq_rpow_eq k c0_sq ck_sq hc0 hck]
  rw [c0_sq_rpow_sub_eq_div k c0_sq hc0]
  ring

theorem C_bound_lem_ineq1_exp1_nonneg (k : ℝ) (hk : (1 : ℝ) ≤ k) :
  (0 : ℝ) ≤ (1 : ℝ) - (1 : ℝ) / k :=
by
  have hk0 : (0 : ℝ) < k := by linarith
  have h_div : (1 : ℝ) / k ≤ (1 : ℝ) := (div_le_one hk0).mpr hk
  linarith

theorem C_bound_lem_ineq1_exp2_nonneg (k : ℝ) (hk : (1 : ℝ) ≤ k) :
  (0 : ℝ) ≤ (1 : ℝ) / k :=
by
  have hk0 : (0 : ℝ) ≤ k := by linarith
  exact div_nonneg zero_le_one hk0

theorem C_bound_lem_ineq1_pow_one_le (x y : ℝ) (hx : (1 : ℝ) ≤ x) (hy : (0 : ℝ) ≤ y) :
  (1 : ℝ) ≤ x ^ y :=
by
  exact Real.one_le_rpow hx hy

theorem C_bound_lem_ineq1_mul_one_le (a b : ℝ) (ha : (1 : ℝ) ≤ a) (hb : (1 : ℝ) ≤ b) :
  (1 : ℝ) ≤ a * b :=
by
  nlinarith

theorem C_bound_lem_ineq1 (k c0_sq ck_sq : ℝ) (hk : (1 : ℝ) ≤ k) (hc0 : (1 : ℝ) ≤ c0_sq) (hck : (1 : ℝ) ≤ ck_sq) :
  (1 : ℝ) ≤ c0_sq ^ ((1 : ℝ) - (1 : ℝ) / k) * ck_sq ^ ((1 : ℝ) / k) :=
by
  have h1 := C_bound_lem_ineq1_exp1_nonneg k hk
  have h2 := C_bound_lem_ineq1_exp2_nonneg k hk
  have h3 := C_bound_lem_ineq1_pow_one_le c0_sq ((1 : ℝ) - (1 : ℝ) / k) hc0 h1
  have h4 := C_bound_lem_ineq1_pow_one_le ck_sq ((1 : ℝ) / k) hck h2
  have h5 := C_bound_lem_ineq1_mul_one_le (c0_sq ^ ((1 : ℝ) - (1 : ℝ) / k)) (ck_sq ^ ((1 : ℝ) / k)) h3 h4
  exact h5

theorem C_bound_lem (k c0_sq ck_sq c12 : ℝ) (hk : (1 : ℝ) ≤ k)
    (hc0 : (1 : ℝ) ≤ c0_sq) (hck : (1 : ℝ) ≤ ck_sq)
    (h_ineq : k * (ck_sq / c0_sq) ^ ((1 : ℝ) / k) ≤ c12 / c0_sq) :
    k ≤ c12 :=
by
  have hc0_pos : 0 < c0_sq := by linarith
  have hck_nonneg : 0 ≤ ck_sq := by linarith
  have hc0_ne_zero : c0_sq ≠ 0 := by linarith

  -- Extract equivalence for simplification
  have hX_eq : c0_sq * (ck_sq / c0_sq) ^ ((1 : ℝ) / k) = c0_sq ^ ((1 : ℝ) - (1 : ℝ) / k) * ck_sq ^ ((1 : ℝ) / k) :=
    C_bound_lem_eq1 k c0_sq ck_sq hc0_pos hck_nonneg

  -- Applying our derived core bound on the equivalence
  have hX_ge_1 : (1 : ℝ) ≤ c0_sq * (ck_sq / c0_sq) ^ ((1 : ℝ) / k) := by
    rw [hX_eq]
    exact C_bound_lem_ineq1 k c0_sq ck_sq hk hc0 hck

  have hk_pos : 0 ≤ k := by linarith

  -- Reconstruct scaled bounding with multiplication over 'k'
  have H1 : k ≤ k * (c0_sq * (ck_sq / c0_sq) ^ ((1 : ℝ) / k)) := by
    calc
      k = k * 1 := (mul_one k).symm
      _ ≤ k * (c0_sq * (ck_sq / c0_sq) ^ ((1 : ℝ) / k)) := mul_le_mul_of_nonneg_left hX_ge_1 hk_pos

  -- Multiply out terms in given base inequality explicitly to match bounds
  have H2 : k * (c0_sq * (ck_sq / c0_sq) ^ ((1 : ℝ) / k)) ≤ c12 := by
    have H2a : (k * (ck_sq / c0_sq) ^ ((1 : ℝ) / k)) * c0_sq ≤ (c12 / c0_sq) * c0_sq :=
      mul_le_mul_of_nonneg_right h_ineq (le_of_lt hc0_pos)
    have H2b : (c12 / c0_sq) * c0_sq = c12 := div_mul_cancel₀ c12 hc0_ne_zero
    have H2c : k * (c0_sq * (ck_sq / c0_sq) ^ ((1 : ℝ) / k)) = (k * (ck_sq / c0_sq) ^ ((1 : ℝ) / k)) * c0_sq := by ring
    rw [H2c]
    rw [H2b] at H2a
    exact H2a

  -- Final bridging over unified bounds
  exact le_trans H1 H2

theorem C_bound (c : ℕ → ℤ) (k : ℕ) (hk : 2 ≤ k) (hc0 : c 0 ≠ 0) (hck : c k ≠ 0)
    (h_ineq : (k : ℝ) * (((c k : ℝ) ^ 2) / ((c 0 : ℝ) ^ 2)) ^ ((1 : ℝ) / (k : ℝ)) ≤ ((c 1 : ℝ) ^ 2 - (2 : ℝ) * (c 0 : ℝ) * (c 2 : ℝ)) / ((c 0 : ℝ) ^ 2)) :
    (k : ℝ) ≤ (c 1 : ℝ) ^ 2 - (2 : ℝ) * (c 0 : ℝ) * (c 2 : ℝ) :=
by
  have hk1 : (1 : ℝ) ≤ (k : ℝ) := one_le_k_of_ge_2 k hk
  have hc0_sq : (1 : ℝ) ≤ (c 0 : ℝ) ^ 2 := int_sq_ge_one (c 0) hc0
  have hck_sq : (1 : ℝ) ≤ (c k : ℝ) ^ 2 := int_sq_ge_one (c k) hck
  exact C_bound_lem (k : ℝ) ((c 0 : ℝ) ^ 2) ((c k : ℝ) ^ 2) ((c 1 : ℝ) ^ 2 - (2 : ℝ) * (c 0 : ℝ) * (c 2 : ℝ)) hk1 hc0_sq hck_sq h_ineq

theorem exists_k_gt_C (C : ℝ) : ∃ k : ℕ, 2 ≤ k ∧ C < (k : ℝ) :=
by
  have ⟨n, hn⟩ := exists_nat_gt C
  use n + 2
  constructor
  · omega
  · push_cast
    linarith

theorem PBBasic006 (c : ℕ → ℤ) (hc : c 0 ≠ 0) : ∃ k, ((∑ i ∈ Finset.Icc 0 k, monomial i (c i)).rootSet ℝ).ncard < k :=
by
  -- Provide a bounding constant using the algebraic derivations (c_1^2 - 2c_0 c_2)
  obtain ⟨k, hk2, hk_gt⟩ := exists_k_gt_C ((c 1 : ℝ) ^ 2 - (2 : ℝ) * (c 0 : ℝ) * (c 2 : ℝ))

  -- Use k as our targeted witness mapping
  use k

  -- Suppose for sake of contradiction that the set contains at least k roots
  by_contra h_roots
  push_neg at h_roots

  -- Translate the context to evaluate rootset via the real polynomial `P_poly`
  have h1 : ((∑ i ∈ Finset.Icc 0 k, monomial i (c i)).rootSet ℝ).ncard = ((P_poly c k).rootSet ℝ).ncard := by
    rw [rootSet_eq_P_poly c k]
  rw [h1] at h_roots

  -- Execute the sub-goals verifying validity iteratively using the sequence of mathematical dependencies
  have hck : c k ≠ 0 := c_k_neq_zero_of_roots hc h_roots
  have hQ_card := Q_roots_card_proof hc h_roots
  have hQ_roots_card := Q_roots_card_eq hc hQ_card
  obtain ⟨h_sum, h_prod⟩ := Q_roots_sum_sq_and_prod hk2 hc hQ_roots_card

  have hk0 : 0 < k := by omega
  have h_am_gm := am_gm_multiset k hk0 (Q_poly c k).roots hQ_roots_card

  -- Apply sum and products directly to formulate AM-GM Inequality equation
  rw [h_sum, h_prod] at h_am_gm

  -- Obtain numerical bound resulting from inequality simplification
  have hk_le := C_bound c k hk2 hc hck h_am_gm

  -- Resolving the directly obtained contradiction `C < k` mapping alongside `k ≤ C`
  linarith
