import Mathlib
open BigOperators
open Finset
open Matrix
def I (x : ℕ) : ℤ := if x > 0 then 1 else 0

theorem sum_seq_int_fin (m : ℕ) (f : Fin (m + 2) → ℤ) :
    ∑ i : Fin (m + 2), f i =
    f 0 * ((m : ℤ) + 2) + ∑ i : Fin (m + 1), (f (Fin.succ i) - f (Fin.castSucc i)) * ((m : ℤ) + 1 - (i : ℤ)) :=
by
  let F : ℕ → ℤ := fun n => if h : n < m + 2 then f ⟨n, h⟩ else 0

  have H : ∀ (m_ : ℕ) (F_ : ℕ → ℤ), ∑ i ∈ Finset.range (m_ + 2), F_ i =
      F_ 0 * ((m_ : ℤ) + 2) + ∑ i ∈ Finset.range (m_ + 1), (F_ (i + 1) - F_ i) * ((m_ : ℤ) + 1 - (i : ℤ)) := by
    intro m_ F_
    induction m_ with
    | zero =>
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      push_cast
      ring
    | succ m_ ih =>
      have h_sub := Finset.sum_range_sub' (fun i => - F_ i) (m_ + 1)
      have H_telescope : ∑ i ∈ Finset.range (m_ + 1), (F_ (i + 1) - F_ i) = F_ (m_ + 1) - F_ 0 := by
        calc ∑ i ∈ Finset.range (m_ + 1), (F_ (i + 1) - F_ i)
          _ = ∑ i ∈ Finset.range (m_ + 1), ((- F_ i) - (- F_ (i + 1))) := by
            apply Finset.sum_congr rfl
            intro x _
            ring
          _ = (- F_ 0) - (- F_ (m_ + 1)) := h_sub
          _ = F_ (m_ + 1) - F_ 0 := by ring

      have H_sum : ∑ i ∈ Finset.range (m_ + 2), (F_ (i + 1) - F_ i) * ((m_ + 1 : ℤ) + 1 - (i : ℤ)) =
          ∑ i ∈ Finset.range (m_ + 1), (F_ (i + 1) - F_ i) * ((m_ : ℤ) + 1 - (i : ℤ)) + F_ (m_ + 2) - F_ 0 := by
        rw [Finset.sum_range_succ]
        have h_eq_sum : ∑ i ∈ Finset.range (m_ + 1), (F_ (i + 1) - F_ i) * ((m_ + 1 : ℤ) + 1 - (i : ℤ)) =
            ∑ i ∈ Finset.range (m_ + 1), (((F_ (i + 1) - F_ i) * ((m_ : ℤ) + 1 - (i : ℤ))) + (F_ (i + 1) - F_ i)) := by
          apply Finset.sum_congr rfl
          intro x _
          push_cast
          ring
        rw [h_eq_sum, Finset.sum_add_distrib, H_telescope]
        push_cast
        ring

      change ∑ i ∈ Finset.range (m_ + 3), F_ i = F_ 0 * ((m_ + 1 : ℤ) + 2) + ∑ i ∈ Finset.range (m_ + 2), (F_ (i + 1) - F_ i) * ((m_ + 1 : ℤ) + 1 - (i : ℤ))
      rw [Finset.sum_range_succ]
      rw [ih]
      rw [H_sum]
      push_cast
      ring

  have hLHS : ∑ i : Fin (m + 2), f i = ∑ i ∈ Finset.range (m + 2), F i := by
    apply Finset.sum_bij (fun i _ => i.val)
    · intro a _
      rw [Finset.mem_range]
      exact a.isLt
    · intro a₁ _ a₂ _ h
      exact Fin.ext h
    · intro b hb
      rw [Finset.mem_range] at hb
      use ⟨b, hb⟩
      refine ⟨Finset.mem_univ _, rfl⟩
    · intro a _
      have F_a : F a.val = f ⟨a.val, a.isLt⟩ := by
        change (if h : a.val < m + 2 then f ⟨a.val, h⟩ else 0) = _
        rw [dif_pos a.isLt]
      rw [F_a]

  have hRHS : ∑ i : Fin (m + 1), (f (Fin.succ i) - f (Fin.castSucc i)) * ((m : ℤ) + 1 - (i : ℤ)) =
              ∑ i ∈ Finset.range (m + 1), (F (i + 1) - F i) * ((m : ℤ) + 1 - (i : ℤ)) := by
    apply Finset.sum_bij (fun i _ => i.val)
    · intro a _
      rw [Finset.mem_range]
      exact a.isLt
    · intro a₁ _ a₂ _ h
      exact Fin.ext h
    · intro b hb
      rw [Finset.mem_range] at hb
      use ⟨b, hb⟩
      refine ⟨Finset.mem_univ _, rfl⟩
    · intro a _
      have h1 : a.val + 1 < m + 2 := by omega
      have h2 : a.val < m + 2 := by omega
      have F1 : F (a.val + 1) = f ⟨a.val + 1, h1⟩ := by
        change (if h : a.val + 1 < m + 2 then f ⟨a.val + 1, h⟩ else 0) = _
        rw [dif_pos h1]
      have F2 : F a.val = f ⟨a.val, h2⟩ := by
        change (if h : a.val < m + 2 then f ⟨a.val, h⟩ else 0) = _
        rw [dif_pos h2]
      have hs : Fin.succ a = ⟨a.val + 1, h1⟩ := Fin.ext rfl
      have hc : Fin.castSucc a = ⟨a.val, h2⟩ := Fin.ext rfl
      rw [hs, hc, F1, F2]

  have hF0 : f 0 = F 0 := by
    have h : 0 < m + 2 := by omega
    have F_0 : F 0 = f ⟨0, h⟩ := by
      change (if h : 0 < m + 2 then f ⟨0, h⟩ else 0) = _
      rw [dif_pos h]
    rw [F_0]
    have h0 : (0 : Fin (m + 2)) = ⟨0, h⟩ := Fin.ext rfl
    rw [h0]

  rw [hLHS, hRHS, hF0]
  exact H m F

theorem sum_I_seq_int_fin (m : ℕ) (f : Fin (m + 2) → ℤ) :
    ∑ i : Fin (m + 2), f i * ((m : ℤ) + 2 - (i : ℤ)) =
    f 0 * ((m : ℤ) + 2) + ∑ i : Fin (m + 1), f (Fin.succ i) * ((m : ℤ) + 1 - (i : ℤ)) :=
by
  -- Expand the summation into `f 0` and a summation over the remaining indices
  rw [Fin.sum_univ_succ]
  -- `congr 1` matches the terms generated by the `+`.
  -- The `f 0` term trivially holds via defeq (since x - 0 = x is defeq in `ℤ`), leaving only the sum target.
  congr 1
  -- Strip the `∑` off to operate inside the bound variables
  apply Finset.sum_congr rfl
  intro i _
  -- Strip the identical `f (Fin.succ i) * ` coefficients on both sides
  congr 1

  -- Reindex the inside and evaluate the shift algebraically
  have hs : (Fin.succ i : ℤ) = (i : ℤ) + 1 := by
    -- Cast Fin.succ to its definitional Nat counterpart
    change ((i.val + 1 : ℕ) : ℤ) = (i : ℤ) + 1
    push_cast
    rfl

  rw [hs]
  ring

theorem sum_col_le_term0 (m : ℕ) (A : Matrix (Fin (m + 2)) (Fin (m + 2)) ℕ)
    (ha : ∀ (i j : Fin (m + 2)), (i : ℕ) + (j : ℕ) ≤ m → A i j = 0)
    (hb : ∀ (i : Fin (m + 1)) (j : Fin (m + 2)),
      A (Fin.succ i) j = A (Fin.castSucc i) j ∨
      A (Fin.succ i) j = A (Fin.castSucc i) j + 1)
    (hc : ∀ (i : Fin (m + 2)) (j : Fin (m + 1)),
      A i (Fin.succ j) = A i (Fin.castSucc j) ∨
      A i (Fin.succ j) = A i (Fin.castSucc j) + 1)
    (j : Fin (m + 2)) :
    (A 0 j : ℤ) * ((m : ℤ) + 2) ≤ I (A 0 j) * ((m : ℤ) + 2) :=
by
  have H : A 0 j = 0 ∨ A 0 j = 1 := by
    by_cases h : (j : ℕ) ≤ m
    · left
      apply ha 0 j
      have h0 : ((0 : Fin (m + 2)) : ℕ) = 0 := by rfl
      omega
    · have hj : (j : ℕ) = m + 1 := by omega
      let k : Fin (m + 1) := ⟨m, by omega⟩
      have hk_val : (k : ℕ) = m := by rfl
      have hjk : j = Fin.succ k := by
        apply Fin.ext
        have h_succ : (Fin.succ k : ℕ) = (k : ℕ) + 1 := by rfl
        omega
      rw [hjk]
      have h_cast : A 0 (Fin.castSucc k) = 0 := by
        apply ha 0 (Fin.castSucc k)
        have h0 : ((0 : Fin (m + 2)) : ℕ) = 0 := by rfl
        have hk_cast : (Fin.castSucc k : ℕ) = (k : ℕ) := by rfl
        omega
      rcases hc 0 k with hc1 | hc2
      · left; omega
      · right; omega
  rcases H with h0 | h1
  · rw [h0]
    have hz : I 0 = (0 : ℤ) := by rfl
    rw [hz]
    omega
  · rw [h1]
    have hI : I 1 = (1 : ℤ) := by rfl
    rw [hI]
    omega

theorem sum_col_le_term_succ (m : ℕ) (A : Matrix (Fin (m + 2)) (Fin (m + 2)) ℕ)
    (hb : ∀ (i : Fin (m + 1)) (j : Fin (m + 2)),
      A (Fin.succ i) j = A (Fin.castSucc i) j ∨
      A (Fin.succ i) j = A (Fin.castSucc i) j + 1)
    (j : Fin (m + 2)) :
    ∑ i : Fin (m + 1), ((A (Fin.succ i) j : ℤ) - (A (Fin.castSucc i) j : ℤ)) * ((m : ℤ) + 1 - (i : ℤ)) ≤
    ∑ i : Fin (m + 1), I (A (Fin.succ i) j) * ((m : ℤ) + 1 - (i : ℤ)) :=
by
  apply Finset.sum_le_sum
  intro i _
  have h_lt := i.isLt
  rcases hb i j with h | h
  · have H : (A (Fin.succ i) j : ℤ) - (A (Fin.castSucc i) j : ℤ) = 0 := by omega
    rw [H]
    unfold I
    split_ifs <;> omega
  · have H : (A (Fin.succ i) j : ℤ) - (A (Fin.castSucc i) j : ℤ) = 1 := by omega
    rw [H]
    unfold I
    split_ifs <;> omega

theorem sum_col_le (m : ℕ) (A : Matrix (Fin (m + 2)) (Fin (m + 2)) ℕ)
    (ha : ∀ (i j : Fin (m + 2)), (i : ℕ) + (j : ℕ) ≤ m → A i j = 0)
    (hb : ∀ (i : Fin (m + 1)) (j : Fin (m + 2)),
      A (Fin.succ i) j = A (Fin.castSucc i) j ∨
      A (Fin.succ i) j = A (Fin.castSucc i) j + 1)
    (hc : ∀ (i : Fin (m + 2)) (j : Fin (m + 1)),
      A i (Fin.succ j) = A i (Fin.castSucc j) ∨
      A i (Fin.succ j) = A i (Fin.castSucc j) + 1)
    (j : Fin (m + 2)) :
    ∑ i : Fin (m + 2), (A i j : ℤ) ≤ ∑ i : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (i : ℤ)) :=
by
  have h1 : ∑ i : Fin (m + 2), (A i j : ℤ) =
    (A 0 j : ℤ) * ((m : ℤ) + 2) + ∑ i : Fin (m + 1), ((A (Fin.succ i) j : ℤ) - (A (Fin.castSucc i) j : ℤ)) * ((m : ℤ) + 1 - (i : ℤ)) :=
    sum_seq_int_fin m (fun i => (A i j : ℤ))
  have h2 : ∑ i : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (i : ℤ)) =
    I (A 0 j) * ((m : ℤ) + 2) + ∑ i : Fin (m + 1), I (A (Fin.succ i) j) * ((m : ℤ) + 1 - (i : ℤ)) :=
    sum_I_seq_int_fin m (fun i => I (A i j))
  rw [h1, h2]
  exact add_le_add (sum_col_le_term0 m A ha hb hc j) (sum_col_le_term_succ m A hb j)

theorem sum_row_le (m : ℕ) (A : Matrix (Fin (m + 2)) (Fin (m + 2)) ℕ)
    (ha : ∀ (i j : Fin (m + 2)), (i : ℕ) + (j : ℕ) ≤ m → A i j = 0)
    (hb : ∀ (i : Fin (m + 1)) (j : Fin (m + 2)),
      A (Fin.succ i) j = A (Fin.castSucc i) j ∨
      A (Fin.succ i) j = A (Fin.castSucc i) j + 1)
    (hc : ∀ (i : Fin (m + 2)) (j : Fin (m + 1)),
      A i (Fin.succ j) = A i (Fin.castSucc j) ∨
      A i (Fin.succ j) = A i (Fin.castSucc j) + 1)
    (i : Fin (m + 2)) :
    ∑ j : Fin (m + 2), (A i j : ℤ) ≤ ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (j : ℤ)) :=
by
  let a : ℕ → ℕ := fun j => if h : j < m + 2 then A i ⟨j, h⟩ else 0

  have ha_pos : ∀ j (h : j < m + 2), a j = A i ⟨j, h⟩ := by
    intro j h
    change (if h' : j < m + 2 then A i ⟨j, h'⟩ else 0) = A i ⟨j, h⟩
    rw [dif_pos h]

  have ha_neg : ∀ j, ¬ (j < m + 2) → a j = 0 := by
    intro j h
    change (if h' : j < m + 2 then A i ⟨j, h'⟩ else 0) = 0
    rw [dif_neg h]

  have ha0 : a 0 ≤ 1 := by
    have h : 0 < m + 2 := by omega
    rw [ha_pos 0 h]
    by_cases hi : (i : ℕ) ≤ m
    · have h_ha_lt : (i : ℕ) + ((⟨0, h⟩ : Fin (m + 2)) : ℕ) ≤ m := by
        change (i : ℕ) + 0 ≤ m
        omega
      have h_ha := ha i ⟨0, h⟩ h_ha_lt
      omega
    · have eq1 : (i : ℕ) = m + 1 := by omega
      let im : Fin (m + 1) := ⟨m, by omega⟩
      have eq2 : i = Fin.succ im := by
        ext
        change (i : ℕ) = m + 1
        omega
      have h_hb := hb im ⟨0, h⟩
      have h_ha_lt : (Fin.castSucc im : ℕ) + ((⟨0, h⟩ : Fin (m + 2)) : ℕ) ≤ m := by
        change m + 0 ≤ m
        omega
      have h_ha := ha (Fin.castSucc im) ⟨0, h⟩ h_ha_lt
      rw [← eq2] at h_hb
      rcases h_hb with hb1 | hb2 <;> omega

  have haj : ∀ j, a (j + 1) ≤ a j + 1 := by
    intro j
    by_cases h_succ : j + 1 < m + 2
    · have h_j : j < m + 2 := by omega
      rw [ha_pos (j + 1) h_succ, ha_pos j h_j]
      let jm : Fin (m + 1) := ⟨j, by omega⟩
      have eq1 : (⟨j + 1, h_succ⟩ : Fin (m + 2)) = Fin.succ jm := by
        ext
        change j + 1 = j + 1
        rfl
      have eq2 : (⟨j, h_j⟩ : Fin (m + 2)) = Fin.castSucc jm := by
        ext
        change j = j
        rfl
      have h_hc := hc i jm
      rw [← eq1, ← eq2] at h_hc
      rcases h_hc with hc1 | hc2 <;> omega
    · rw [ha_neg (j + 1) h_succ]
      omega

  have I_nonneg : ∀ x, 0 ≤ I x := by
    intro x
    unfold I
    split
    · omega
    · omega

  have H1 : ∀ n, (a n : ℤ) ≤ ∑ j ∈ Finset.range (n + 1), I (a j) := by
    intro n
    induction n with
    | zero =>
      have h_sum_succ : ∑ j ∈ Finset.range (0 + 1), I (a j) = ∑ j ∈ Finset.range 0, I (a j) + I (a 0) := Finset.sum_range_succ (fun j => I (a j)) 0
      have h_sum0 : ∑ j ∈ Finset.range 0, I (a j) = 0 := Finset.sum_range_zero _
      rw [h_sum_succ, h_sum0, zero_add]
      have h_cases : a 0 = 0 ∨ a 0 = 1 := by omega
      rcases h_cases with h_case | h_case
      · rw [h_case]
        have hI : I 0 = 0 := rfl
        omega
      · rw [h_case]
        have hI : I 1 = 1 := rfl
        omega
    | succ n ih =>
      have h_sum : ∑ j ∈ Finset.range (n + 1 + 1), I (a j) = ∑ j ∈ Finset.range (n + 1), I (a j) + I (a (n + 1)) := Finset.sum_range_succ (fun j => I (a j)) (n + 1)
      rw [h_sum]
      have hn : (a (n + 1) : ℤ) ≤ (a n : ℤ) + 1 := by
        have := haj n
        omega
      by_cases h_z : a (n + 1) = 0
      · rw [h_z]
        have h1 : 0 ≤ ∑ j ∈ Finset.range (n + 1), I (a j) := Finset.sum_nonneg (fun j _ => I_nonneg (a j))
        have h2 : I 0 = 0 := rfl
        omega
      · have h_pos : a (n + 1) > 0 := by omega
        have h_I : I (a (n + 1)) = (1 : ℤ) := by
          unfold I
          rw [if_pos h_pos]
        linarith

  have H2 : ∀ n, ∑ j ∈ Finset.range n, (a j : ℤ) ≤ ∑ j ∈ Finset.range n, I (a j) * ((n : ℤ) - (j : ℤ)) := by
    intro n
    induction n with
    | zero =>
      simp
    | succ n ih =>
      have h_lhs_succ : ∑ j ∈ Finset.range (n + 1), (a j : ℤ) = ∑ j ∈ Finset.range n, (a j : ℤ) + (a n : ℤ) := Finset.sum_range_succ (fun j => (a j : ℤ)) n
      have h_rhs_succ : ∑ j ∈ Finset.range (n + 1), I (a j) * (((n + 1 : ℕ) : ℤ) - (j : ℤ)) = ∑ j ∈ Finset.range n, I (a j) * (((n + 1 : ℕ) : ℤ) - (j : ℤ)) + I (a n) * (((n + 1 : ℕ) : ℤ) - (n : ℤ)) := Finset.sum_range_succ (fun j => I (a j) * (((n + 1 : ℕ) : ℤ) - (j : ℤ))) n
      rw [h_lhs_succ, h_rhs_succ]
      have h_rewrite : ∑ j ∈ Finset.range n, I (a j) * (((n + 1 : ℕ) : ℤ) - (j : ℤ)) = ∑ j ∈ Finset.range n, (I (a j) * ((n : ℤ) - (j : ℤ)) + I (a j)) := by
        apply Finset.sum_congr rfl
        intro j _
        push_cast
        ring
      rw [h_rewrite, Finset.sum_add_distrib]
      have h_last : I (a n) * (((n + 1 : ℕ) : ℤ) - (n : ℤ)) = I (a n) := by
        push_cast
        ring
      rw [h_last]
      have h_a_n := H1 n
      have h_sum_I : ∑ j ∈ Finset.range (n + 1), I (a j) = ∑ j ∈ Finset.range n, I (a j) + I (a n) := Finset.sum_range_succ (fun j => I (a j)) n
      rw [h_sum_I] at h_a_n
      linarith

  have h_lhs : ∑ j : Fin (m + 2), (A i j : ℤ) = ∑ j ∈ Finset.range (m + 2), (a j : ℤ) := by
    have eq1 : ∑ j ∈ Finset.range (m + 2), (a j : ℤ) = ∑ j : Fin (m + 2), (a (j : ℕ) : ℤ) :=
      (Fin.sum_univ_eq_sum_range (fun k => (a k : ℤ)) (m + 2)).symm
    rw [eq1]
    apply Finset.sum_congr rfl
    intro j _
    have h : (j : ℕ) < m + 2 := j.isLt
    have eq_a : a (j : ℕ) = A i j := ha_pos (j : ℕ) h
    rw [eq_a]

  have h_rhs : ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (j : ℤ)) = ∑ j ∈ Finset.range (m + 2), I (a j) * (((m + 2 : ℕ) : ℤ) - (j : ℤ)) := by
    have eq1 : ∑ j ∈ Finset.range (m + 2), I (a j) * (((m + 2 : ℕ) : ℤ) - (j : ℤ)) = ∑ j : Fin (m + 2), I (a (j : ℕ)) * (((m + 2 : ℕ) : ℤ) - ((j : ℕ) : ℤ)) :=
      (Fin.sum_univ_eq_sum_range (fun k => I (a k) * (((m + 2 : ℕ) : ℤ) - (k : ℤ))) (m + 2)).symm
    rw [eq1]
    apply Finset.sum_congr rfl
    intro j _
    have h : (j : ℕ) < m + 2 := j.isLt
    have eq_a : a (j : ℕ) = A i j := ha_pos (j : ℕ) h
    rw [eq_a]
    push_cast
    ring

  rw [h_lhs, h_rhs]
  exact H2 (m + 2)

theorem A_le_I (m : ℕ) (A : Matrix (Fin (m + 2)) (Fin (m + 2)) ℕ)
    (ha : ∀ (i j : Fin (m + 2)), (i : ℕ) + (j : ℕ) ≤ m → A i j = 0)
    (hb : ∀ (i : Fin (m + 1)) (j : Fin (m + 2)),
      A (Fin.succ i) j = A (Fin.castSucc i) j ∨
      A (Fin.succ i) j = A (Fin.castSucc i) j + 1)
    (hc : ∀ (i : Fin (m + 2)) (j : Fin (m + 1)),
      A i (Fin.succ j) = A i (Fin.castSucc j) ∨
      A i (Fin.succ j) = A i (Fin.castSucc j) + 1)
    (i j : Fin (m + 2)) :
    (A i j : ℤ) ≤ I (A i j) * ((i : ℤ) + (j : ℤ) - (m : ℤ)) :=
by
  have H : ∀ (u v : Fin (m + 2)), (m : ℤ) < (u : ℤ) + (v : ℤ) → (A u v : ℤ) ≤ (u : ℤ) + (v : ℤ) - (m : ℤ) := by
    intro u
    induction u using Fin.induction with
    | zero =>
      intro v
      induction v using Fin.induction with
      | zero =>
        intro h
        have h0n : ((0 : Fin (m + 2)) : ℕ) = 0 := rfl
        have h0z : ((0 : Fin (m + 2)) : ℤ) = 0 := rfl
        omega
      | succ v_step ih =>
        intro h
        have h0n : ((0 : Fin (m + 2)) : ℕ) = 0 := rfl
        have h0z : ((0 : Fin (m + 2)) : ℤ) = 0 := rfl
        have hvn : (Fin.castSucc v_step : ℕ) = (v_step : ℕ) := rfl
        have hvz : (Fin.castSucc v_step : ℤ) = (v_step : ℤ) := rfl
        have hv_succn : (Fin.succ v_step : ℕ) = (v_step : ℕ) + 1 := rfl
        have hv_succz : (Fin.succ v_step : ℤ) = (v_step : ℤ) + 1 := by omega
        by_cases h_le : ((0 : Fin (m + 2)) : ℕ) + (Fin.castSucc v_step : ℕ) ≤ m
        · have ha_val := ha (0 : Fin (m + 2)) (Fin.castSucc v_step) h_le
          rcases hc (0 : Fin (m + 2)) v_step with hc1 | hc2 <;> omega
        · have h_gt : (m : ℤ) < ((0 : Fin (m + 2)) : ℤ) + (Fin.castSucc v_step : ℤ) := by omega
          have ih_val := ih h_gt
          rcases hc (0 : Fin (m + 2)) v_step with hc1 | hc2 <;> omega
    | succ u_step uh =>
      intro v
      have hun : (Fin.castSucc u_step : ℕ) = (u_step : ℕ) := rfl
      have huz : (Fin.castSucc u_step : ℤ) = (u_step : ℤ) := rfl
      have hu_succn : (Fin.succ u_step : ℕ) = (u_step : ℕ) + 1 := rfl
      have hu_succz : (Fin.succ u_step : ℤ) = (u_step : ℤ) + 1 := by omega
      intro h
      by_cases h_le : (Fin.castSucc u_step : ℕ) + (v : ℕ) ≤ m
      · have ha_val := ha (Fin.castSucc u_step) v h_le
        rcases hb u_step v with hb1 | hb2 <;> omega
      · have h_gt : (m : ℤ) < (Fin.castSucc u_step : ℤ) + (v : ℤ) := by omega
        have ih_val := uh v h_gt
        rcases hb u_step v with hb1 | hb2 <;> omega

  by_cases hA : A i j = 0
  · have h_not_pos : ¬(A i j > 0) := by omega
    have hI : I (A i j) = 0 := by
      unfold I
      exact if_neg h_not_pos
    rw [hI]
    omega
  · have hA_pos : A i j > 0 := by omega
    have hI : I (A i j) = 1 := by
      unfold I
      exact if_pos hA_pos
    have h_gt : (m : ℤ) < (i : ℤ) + (j : ℤ) := by
      by_cases h_le : (i : ℕ) + (j : ℕ) ≤ m
      · have h_zero : A i j = 0 := ha i j h_le
        omega
      · omega
    have h_H := H i j h_gt
    rw [hI]
    omega

theorem sum_I_eq_N (m : ℕ) (A : Matrix (Fin (m + 2)) (Fin (m + 2)) ℕ)
    (N : ℕ) (hN : N = #{p : Fin (m + 2) × Fin (m + 2) | A p.1 p.2 ≠ 0}) :
    ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) = (N : ℤ) :=
by
  -- Convert I to an explicit check against ≠ 0
  have hI : ∀ i j, I (A i j) = if A i j ≠ 0 then (1 : ℤ) else 0 := by
    intro i j
    unfold I
    by_cases h : A i j = 0
    · have h1 : ¬(A i j > 0) := by omega
      have h2 : ¬(A i j ≠ 0) := by omega
      rw [if_neg h1, if_neg h2]
    · have h1 : A i j > 0 := by omega
      have h2 : A i j ≠ 0 := by omega
      rw [if_pos h1, if_pos h2]

  calc
    (∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j))
      = ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), if A i j ≠ 0 then (1 : ℤ) else 0 := by
        apply Finset.sum_congr rfl
        intro i _
        apply Finset.sum_congr rfl
        intro j _
        exact hI i j

    -- Relate nested sum to sum over the product type.
    _ = ∑ p ∈ (Finset.univ : Finset (Fin (m + 2))) ×ˢ (Finset.univ : Finset (Fin (m + 2))), if A p.1 p.2 ≠ 0 then (1 : ℤ) else 0 := by
        exact (Finset.sum_product (Finset.univ : Finset (Fin (m + 2))) (Finset.univ : Finset (Fin (m + 2))) (fun p : Fin (m + 2) × Fin (m + 2) => if A p.1 p.2 ≠ 0 then (1 : ℤ) else 0)).symm

    _ = ∑ p : Fin (m + 2) × Fin (m + 2), if A p.1 p.2 ≠ 0 then (1 : ℤ) else 0 := by
        apply Finset.sum_congr
        · ext p; simp
        · intro p _; rfl

    -- Relate the `if-then-else` boolean mapping strictly onto a filtered `Finset` sum.
    _ = ∑ p ∈ (Finset.univ : Finset (Fin (m + 2) × Fin (m + 2))).filter (fun p => A p.1 p.2 ≠ 0), (1 : ℤ) := by
        rw [← Finset.sum_filter]

    -- The sum of a unit coefficient `1` bounds down perfectly to the `Finset.card`.
    _ = (((Finset.univ : Finset (Fin (m + 2) × Fin (m + 2))).filter (fun p => A p.1 p.2 ≠ 0)).card : ℤ) := by
        rw [Finset.sum_const, nsmul_eq_mul, mul_one]

    -- Final extraction step: Strip external type castings and inject hypothesis N bounding.
    _ = (N : ℤ) := by
        congr 1
        rw [hN]

theorem putnam_2025_b4 (m : ℕ)
    (A : Matrix (Fin (m + 2)) (Fin (m + 2)) ℕ)
    (ha : ∀ (i j : Fin (m + 2)), (i : ℕ) + (j : ℕ) ≤ m → A i j = 0)
    (hb : ∀ (i : Fin (m + 1)) (j : Fin (m + 2)),
      A (Fin.succ i) j = A (Fin.castSucc i) j ∨
      A (Fin.succ i) j = A (Fin.castSucc i) j + 1)
    (hc : ∀ (i : Fin (m + 2)) (j : Fin (m + 1)),
      A i (Fin.succ j) = A i (Fin.castSucc j) ∨
      A i (Fin.succ j) = A i (Fin.castSucc j) + 1)
    (S : ℕ)
    (hS : S = ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), A i j)
    (N : ℕ)
    (hN : N = #{p : Fin (m + 2) × Fin (m + 2) | A p.1 p.2 ≠ 0}) : 3 * S ≤ (m + 4) * N :=
by

  have hS_int : (S : ℤ) = ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), (A i j : ℤ) := by
    rw [hS]
    push_cast
    rfl

  -- Bound 1: Column-wise differences
  have hS_col : (S : ℤ) ≤ ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (i : ℤ)) := by
    rw [hS_int]
    calc
      ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), (A i j : ℤ)
        = ∑ j : Fin (m + 2), ∑ i : Fin (m + 2), (A i j : ℤ) := Finset.sum_comm
      _ ≤ ∑ j : Fin (m + 2), ∑ i : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (i : ℤ)) := Finset.sum_le_sum (fun j _ => sum_col_le m A ha hb hc j)
      _ = ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (i : ℤ)) := Finset.sum_comm

  -- Bound 2: Row-wise differences
  have hS_row : (S : ℤ) ≤ ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (j : ℤ)) := by
    rw [hS_int]
    exact Finset.sum_le_sum (fun i _ => sum_row_le m A ha hb hc i)

  -- Bound 3: Absolute distance indicator distances
  have hS_dist : (S : ℤ) ≤ ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((i : ℤ) + (j : ℤ) - (m : ℤ)) := by
    rw [hS_int]
    exact Finset.sum_le_sum (fun i _ => Finset.sum_le_sum (fun j _ => A_le_I m A ha hb hc i j))

  -- Summing the triple bounds
  have hS_3 : 3 * (S : ℤ) ≤ ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 4) := by
    calc
      3 * (S : ℤ) = (S : ℤ) + (S : ℤ) + (S : ℤ) := by ring
      _ ≤ (∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (i : ℤ))) +
          (∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 2 - (j : ℤ))) +
          (∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((i : ℤ) + (j : ℤ) - (m : ℤ))) := add_le_add (add_le_add hS_col hS_row) hS_dist
      _ = ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), (I (A i j) * ((m : ℤ) + 2 - (i : ℤ)) + I (A i j) * ((m : ℤ) + 2 - (j : ℤ)) + I (A i j) * ((i : ℤ) + (j : ℤ) - (m : ℤ))) := by
        simp_rw [← Finset.sum_add_distrib]
      _ = ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 4) := by
        apply Finset.sum_congr rfl
        intro i _
        apply Finset.sum_congr rfl
        intro j _
        ring

  -- Extracting outer indicator terms and substituting N support
  have hS_4 : ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 4) = ((m : ℤ) + 4) * (N : ℤ) := by
    calc
      ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 4)
        = (∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j)) * ((m : ℤ) + 4) := by simp_rw [Finset.sum_mul]
      _ = (N : ℤ) * ((m : ℤ) + 4) := by rw [sum_I_eq_N m A N hN]
      _ = ((m : ℤ) + 4) * (N : ℤ) := by ring

  have h_final_int : 3 * (S : ℤ) ≤ ((m : ℤ) + 4) * (N : ℤ) := by
    calc 3 * (S : ℤ) ≤ ∑ i : Fin (m + 2), ∑ j : Fin (m + 2), I (A i j) * ((m : ℤ) + 4) := hS_3
      _ = ((m : ℤ) + 4) * (N : ℤ) := hS_4

  -- Push Nat cast resolution to complete closure
  have h_cast : ((3 * S : ℕ) : ℤ) ≤ (((m + 4) * N : ℕ) : ℤ) := by
    push_cast
    exact h_final_int
  exact Nat.cast_le.mp h_cast
